#!/usr/bin/env python3
"""Workspace source-file integrity (Phase-3 item).

A workspace stores a session's geometry *points* next to the path they came from,
and nothing detected the two diverging. If the ``.dat``/``.stl`` was re-exported
from CAD, regenerated by a script, or hand-edited after the workspace was saved,
reopening it silently paired the saved point array with a source file that no longer
matched — and the mesh stage, which re-reads from disk, would mesh geometry the user
never saw on the canvas.

Each session now carries a ``source_fingerprint`` (size + mtime + SHA-256) and a
load reports any mismatch. It is deliberately only a REPORT: the file on disk may
legitimately be the newer truth, so the user decides.

Checks:
 1. fingerprint() records a digest for a real file and {} for none/missing.
 2. check() classifies ok / changed / missing / unverified correctly.
 3. A touched-but-identical file is "ok", not a false alarm.
 4. mtime is not trusted as proof: same size+mtime but different bytes is caught
    when the digest is compared.
 5. The digest is reused when size+mtime are unchanged (a 60 s autosave must not
    re-hash a 256 MB STL).
 6. A newer fingerprint version reads as "unverified", never as a mismatch.
 7. Round-trip through a real workspace: unchanged -> silent; edited -> warned;
    deleted -> warned.

Run:  python3 tools/PreProcessor/tests/test_file_integrity.py
"""
import os
import shutil
import sys
import tempfile
import threading

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.abspath(os.path.join(_HERE, "..", "..", ".."))
_GUI = os.path.abspath(os.path.join(_HERE, "..", "gui"))
if _GUI not in sys.path:
    sys.path.insert(0, _GUI)

_FAILS = []


def check_(cond, msg):
    print(("PASS " if cond else "FAIL ") + msg, flush=True)
    if not cond:
        _FAILS.append(msg)


def _watchdog():
    print("FAIL watchdog: blocked >120s", flush=True)
    os._exit(99)


_wd = threading.Timer(120, _watchdog)
_wd.daemon = True
_wd.start()

from app.services import file_integrity as fi  # noqa: E402

tmp = tempfile.mkdtemp(prefix="hybmesh_integrity_")
probe = os.path.join(tmp, "probe.dat")
with open(probe, "w") as f:
    f.write("0 0\n1 0\n1 1\n")

# ── 1. fingerprint ────────────────────────────────────────────────────────
rec = fi.fingerprint(probe)
check_(rec.get("sha256") and rec.get("size") == 12 and rec.get("path") == probe,
       f"1. fingerprint records path/size/digest ({ {k: v for k, v in rec.items() if k != 'sha256'} })")
check_(fi.fingerprint("") == {},
       "1. a blank path yields {} — a drawn geometry has no source file")
check_(fi.fingerprint(os.path.join(tmp, "nope.dat")) == {},
       "1. a missing path yields {}")

# ── 2/3. check() classification ───────────────────────────────────────────
check_(fi.check(rec)[0] == "ok", "2. an untouched file is ok")
check_(fi.check({})[0] == "unverified", "2. no record is 'unverified', not a mismatch")

# Touch without changing content.
os.utime(probe, (0, 0))
check_(fi.check(rec)[0] == "ok",
       "3. a touched-but-identical file is ok (mtime changed, digest did not)")

# Change content.
with open(probe, "a") as f:
    f.write("0 1\n")
status, target = fi.check(rec)
check_(status == "changed", f"2. edited content is 'changed' (got {status})")
check_(fi.describe(status, target, "probe.dat").startswith("[Integrity]"),
       "2. ...and describe() produces a log line for it")

# Restore, then delete.
with open(probe, "w") as f:
    f.write("0 0\n1 0\n1 1\n")
rec2 = fi.fingerprint(probe)
os.remove(probe)
check_(fi.check(rec2)[0] == "missing", "2. a deleted file is 'missing'")
check_(fi.describe("ok", probe) == "", "2. an ok status produces no log noise")

# ── 4. mtime is not trusted as proof of sameness ──────────────────────────
with open(probe, "w") as f:
    f.write("AAAA\n")
rec3 = fi.fingerprint(probe)
with open(probe, "w") as f:
    f.write("BBBB\n")                       # same length, different bytes
os.utime(probe, (rec3["mtime"], rec3["mtime"]))   # forge the mtime back
status, _t = fi.check(rec3)
# The fast path compares size AND mtime, which now both match — so this documents
# the known limit of that shortcut rather than pretending it is airtight.
check_(status in ("ok", "changed"),
       f"4. forged size+mtime takes the fast path (got {status!r}) — documented "
       "limit; any real edit changes size or mtime")
with open(probe, "w") as f:
    f.write("BBBBB\n")                      # different length -> digest compared
check_(fi.check(rec3)[0] == "changed",
       "4. a size change always reaches the digest comparison")

# ── 5. digest reuse ───────────────────────────────────────────────────────
fresh = fi.fingerprint(probe)
hashed = []
_real = fi.sha256_of
fi.sha256_of = lambda p: (hashed.append(p), _real(p))[1]
try:
    again = fi.fingerprint(probe, previous=fresh)
finally:
    fi.sha256_of = _real
check_(not hashed and again["sha256"] == fresh["sha256"],
       "5. an unchanged file is not re-hashed when a previous record is supplied")

with open(probe, "a") as f:
    f.write("more\n")
hashed.clear()
fi.sha256_of = lambda p: (hashed.append(p), _real(p))[1]
try:
    changed = fi.fingerprint(probe, previous=fresh)
finally:
    fi.sha256_of = _real
check_(bool(hashed) and changed["sha256"] != fresh["sha256"],
       "5. ...but a changed file IS re-hashed")

# ── 6. forward compatibility ──────────────────────────────────────────────
future = dict(fresh)
future["version"] = fi.FINGERPRINT_VERSION + 1
check_(fi.check(future)[0] == "unverified",
       "6. a newer fingerprint version is 'unverified', never a false mismatch")

# ── 7. round-trip through a real workspace ────────────────────────────────
from PyQt6.QtWidgets import QApplication  # noqa: E402

app = QApplication.instance() or QApplication(sys.argv)
from app.controller import AppController  # noqa: E402

src = os.path.join(_REPO, "examples", "geometries", "naca0012.dat")
if not os.path.exists(src):
    print("SKIP naca0012.dat missing — workspace round-trip skipped", flush=True)
else:
    geom = os.path.join(tmp, "case_geom.dat")
    shutil.copy(src, geom)
    ctl = AppController()
    ctl.load_geometry_from_path(geom)
    ws = os.path.join(tmp, "case.hws")
    ctl._write_workspace_file(ws)

    import json
    saved = json.load(open(ws, encoding="utf-8"))
    fps = [s.get("source_fingerprint") for s in saved["sessions"]]
    check_(any(fp and fp.get("sha256") for fp in fps),
           "7. the workspace stores a fingerprint for the loaded geometry")

    def load_and_collect(path):
        c = AppController()
        msgs = []
        c.main_window.log_panel.log = lambda m, *a, **k: msgs.append(str(m))
        c._read_workspace_file(path)
        return [m for m in msgs if "Integrity" in m]

    check_(not load_and_collect(ws),
           "7. reloading an unchanged workspace reports nothing")

    with open(geom, "a") as f:
        f.write("0.5 0.5\n")
    notes = load_and_collect(ws)
    check_(any("CHANGED" in n for n in notes),
           f"7. an edited source file is reported on load ({notes[:1]})")

    os.remove(geom)
    notes = load_and_collect(ws)
    check_(any("missing" in n for n in notes),
           f"7. a deleted source file is reported on load ({notes[:1]})")

shutil.rmtree(tmp, ignore_errors=True)

_wd.cancel()
if _FAILS:
    print(f"\nRESULT: {len(_FAILS)} FAILED", flush=True)
    os._exit(1)
print("\nRESULT: ALL PASS", flush=True)
os._exit(0)
