#!/usr/bin/env python3
"""The C-grid template: a wake CUT and a four-way trailing-edge corner (#148).

The H-grid proved the chain from a parameter form to a mesh; the O-grid added the
BINDING and the refusal when one breaks. This family adds no third mechanism — it is
a registry entry, a field-spec table and a function — and what it has to be measured
on is therefore not the machinery but the two STRUCTURES that made
``examples/topology/cgrid_naca0012.json`` the hardest of the shipped documents to
have typed by hand:

  * the wake is ONE ``cut`` edge that is the WEST of BOTH wake blocks, and
  * the trailing edge is ONE declared corner where all four blocks meet.

WHAT THIS FILE FOUND ABOUT THE SHARED INVARIANT CHECKER, and did not work around.
``topology_doc_invariants.ring_closes`` used to require a block's east, north and west
to be declared in the convention's own direction; the mesher does not, and cannot,
because a shared edge is ONE edge with ONE direction named by two blocks whose frames
need not agree about it. Run against the SHIPPED, WORKING, hand-written C-grid that
check returned one complaint — and no C-grid can ever satisfy it, since the cut is the
west of both wake blocks and the two want it declared opposite ways round. The checker
now mirrors ``resolveBlockFrames`` exactly (and gained the mesher's distinct-corner
refusal with it); the H-grid's own injection A — east and west swapped — still fails it,
and so does a reversed SOUTH edge, which the mesher also refuses because south is what
fixes the frame.

THE FAR FIELD IS GENERATED BY DEFAULT AND OPTIONALLY DRAWN (#149). #148's own demo is
"fill in wake length, far-field radius and target cell edge", so with no far-field
geometry named the six far-field corners are FREE coordinates and their edges are the
straight lines between them — which is still the default and is not a degraded state.
Two consequences, both MEASURED here rather than argued: check 13 shows those six
corners landing exactly on the shipped hand-written document's, and check 14c reports
what the hexagon costs against the shipped curved D — the peak non-orthogonality, at the
one corner where they differ, and nothing at the wall. The third is not a measurement
but a limitation: a free corner belongs to no geometry, so those six sides carry the
run's ``BC_GEOM`` and cannot carry an ``outlet`` of their own (check 14b2, against the
shipped document's two names in 14d).

#149 IS THE OTHER PATH, AND IT IS A BRANCH RATHER THAN A MECHANISM. Naming a far-field
geometry cut into SIX segments turns those six corners into corners OF IT and binds the
six sides to its segments, so each side carries the condition on its own — checked in
section 18, and measured through the real mesher in 14f-14h: the SAME three boundary
names the shipped hand-written document exports, the hexagon's peak non-orthogonality
gone (1.05x the shipped case where the generated path is 1.63x), and the grid at the
section unmoved. Everything that makes that work is #137's and #138's, unchanged. What
is this family's OWN is the pair of measurements nothing else could make: where the
drawn ring STARTS and which way it WINDS are both binding information here, where the
O-grid's ring has no first segment — and neither is visible to a binding check, because
under both every id still resolves and every side still lies on its own segment
(checks 18e and 18f).

WHAT THIS FILE DOES NOT CHECK, because another gate owns it: the structural rules
themselves (``topology_doc_invariants.py``, which checks 1-7 call and which both other
family gates call too), the parameters-to-families comparison
(``test_topology_param_specs.py``), what the panel displays (``test_topology_panel.py``),
that the model persists (``test_topology_persistence.py``) and the aerofoil CAD shape
itself (``test_naca_airfoil_parity.py``, #147).

INJECTIONS: run by hand, 2026-09-24, each reverted and the tree compared against its
pre-injection state afterwards. Each line is what the mutation ACTUALLY did, READ FROM
THE EXIT CODE and not from a count of FAIL lines. Where the result differed from the
prediction written first, the correction is the record.

  A. the upper surface is always the one LEAVING the trailing edge (the cross-product
     measurement deleted) -> exit 1, checks 9 and 9b. NOT 9c: the mirrored section's
     rings still wind counter-clockwise, because the far field is laid out in world
     axes and only the surface edges' direction changed — which is the same fact this
     family rests on, seen from the other side.
  B. the wake declared ``interface`` instead of ``cut`` -> exit 1, checks 8 and 8c.
     The document is otherwise LEGAL — an interface bounds two blocks too, so checks
     2, 4, 5 and 7 all stay green and the mesher meshes it; what is lost is the
     declaration that this line is a cut, which #57's own note says is DECLARED here
     rather than inferred from the absence of a binding.
  D. the blunt-trailing-edge refusal removed -> exit 1, check 12 ALONE, and that is
     the useful part: the section is still refused, by the "exactly two surfaces"
     count one line below, so what the injection removes is the SENTENCE and not the
     safety. 12 goes red on the wording, which is what the criterion asks for ("with
     the problem named").
  E. the far field's nose placed ahead of the TRAILING edge rather than the leading
     one -> exit 1, check 13 alone. Nothing else can see it: the document is legal,
     it meshes, and only the comparison against the shipped hand-written corners
     knows where f2 belongs.
  F. ``GROWTH`` 1.2 -> 1.5 -> exit 1, check 11b alone (43 radial nodes became 23,
     against the shipped document's 41). Predicted "11b and 14"; the mesher meshes
     the coarser grid to zero inverted cells, so the real binary cannot see it.
  H. ``ring_closes`` put back to the version that pinned every side's direction ->
     exit 1, check 2 alone, on ``b_wake_up`` of every document in the spread. This is
     the negative control for the relaxation itself: without it this family's own
     output fails the shared checker exactly as the shipped hand-written document did.
  J. the two wake blocks name the cut as their SOUTH instead of their west -> exit 1,
     TWELVE checks (2, 4, 8, 9c, the whole 14 series and 16b/16c). The blast radius is
     the point: naming the same four edges in a different order is not a relabelling,
     it re-frames both blocks, and the real mesher refuses the document.

#149's OWN, run by hand 2026-09-29 with ``PYTHONDONTWRITEBYTECODE=1`` (see below),
each reverted and the file's sha256 compared against its pre-injection one. Read from
the exit code, not from a count of FAIL lines.

  K. ``resolve_far`` never binds — a named geometry silently keeps the generated path
     -> exit 1, NINE checks (18b-18i, 14f, 14g). The blast radius is the point: the
     whole of #149 is that ONE return.
  L. the nose-position measurement deleted -> exit 1, check 18f ALONE. Nothing else
     can see it: a far field drawn starting at the next joint along resolves every id,
     lies every side on its own segment, passes order and cover, winds the right way
     and then folds the four blocks.
  M. the winding measurement deleted -> exit 1, check 18e alone, for the same reason
     one joint round.
  N. the six-segment count relaxed to any count -> exit 1, checks 18d and 18i.
  P. the two spans read back from ``cgrid_wake_length`` / ``cgrid_far_radius`` instead
     of being measured off the placed corners -> exit 1, check 18c alone. NOT 18c2,
     which corrects the prediction written first: on the fixture the drawn far field
     sits exactly where the two lengths would generate one, so the numbers agree and
     only the absurd-lengths document tells them apart.
  Q. the far-field half of ``broken_bindings`` removed -> exit 1, checks 18h and 10d.
     10d is the useful half: with the loop collapsed onto the section list the section
     is reported TWICE, so a copy-paste of the row that reports it is caught from the
     other direction.
  R. the six sides bound one position along -> exit 1, checks 18b, 14f, 14g and 14h.
  S. the sides bound but the corners left FREE -> exit 1, 18b, 14f, 14g, 14h.
  T. the corners bound but the sides left unbound -> exit 1, 18b, 14f, 14g. Not 14h:
     the grid at the section is unmoved, which is exactly what 14h says.
  U. the drawn far field's containment tested on its six corner CHORDS rather than on
     its own polylines -> exit 1, check 18c3 alone. Its FIRST version was INERT — the
     aerofoil sits well inside either ring — and the check was rewritten to measure
     the two rings apart directly (the drawn one encloses 1.137x the area over 210
     points against 6) rather than to hope a fixture would fall between them.
  V. ``BINDING_ROWS`` loses the C-grid's far pair -> this file stays GREEN and
     ``test_topology_panel.py`` check 13g goes red, which is the right split: the
     capture is the panel's, and the family never reads a widget.

#149's REVIEW ROUND, 2026-09-29, same harness. Both axes found the same mislabelled
check (18i's "not a closed loop" case fed the two-segment aerofoil and reached the
COUNT refusal, leaving `resolve_far`'s closed-loop branch reached by nothing), which
is this file's own recurring finding one more time: a check narrower than its label.

  Y.  the zero-area half of the ring measurement deleted -> exit 1, check 18f2.
      INERT before that check existed, which is how the defect got in: `signed_area`
      answers 0.0 both for a ring enclosing nothing and for one whose corners cannot
      be placed, and its own docstring says a caller must report that rather than
      read a DIRECTION off it. `<= 0.0` told the user to redraw a degenerate outline
      backwards AND left the no-length refusal below it unreachable. Two fixtures
      now reach it (`far-flat`, `far-zero`).
  Y2. the whole pre-review ORDER put back — direction measured before the corners
      are placed -> exit 1, check 18f2. The negative control for the fix itself.
  Z.  the resolve half of `held_bindings` dropped -> exit 1, checks 10c and 18g, one
      per list: the shared spine really is what names the edge for BOTH.
  AA. the closed-loop refusal removed -> exit 1, check 18i, which now feeds a
      six-segment outline that does not close instead of one the count refuses.
  W.  an `INERT_WHEN_BOUND` entry naming no field-spec row -> `test_topology_param_
      specs.py` check 10b. W2, naming ANOTHER family's row -> the same check. A name
      that is no row greys nothing, and the control goes on looking live.
  X.  the greying dropped from `_refresh_topology_detach` -> `test_topology_panel.py`
      check 13h2. That loop is the ONE owner of a topology row's enabled state: the
      first version of this greyed the rows in `_refresh_topology_counts` and was
      silently undone by the detach refresh on every keystroke.

  THE FIRST RUN OF THIS HARNESS WAS WRONG TWICE, and both corrections are in the tree
  rather than in this comment. (i) Apple's python3 caches bytecode OUTSIDE the tree
  (``~/Library/Caches/com.apple.python``) and validates it by ``(mtime, size)``, so a
  restore at the SAME SIZE — ``x_le`` for ``x_te`` is exactly that — was silently
  ignored: ``git status`` was clean, the source file read correctly, and
  ``far_corners`` still answered with the mutation. Bumping the mtime was not enough;
  the harness now runs with ``PYTHONDONTWRITEBYTECODE=1``. (ii) Two injections CRASHED
  this file part-way (B at check 8c, J inside the winding walk), so they measured as
  2 and 3 checks; both sites were guarded, and J then measured as TWELVE. A crash is
  not a weak bite, it is an unmeasured one.

NAMED BLIND SPOTS:

  * Nothing here drives the GUI. That the panel captures the aerofoil's binding when
    the user names it, shows this derivation and flags a broken one is
    ``test_topology_panel.py``'s and ``test_topology_repair.py``'s. Checks 16-17d go
    one layer further out than the rest of this file — through the real
    ``MeshConfig`` and the real skeleton and detach services, which is what the canvas
    mixin and the panel's buttons are handed — but they still call no Qt.
  * The far field's SIX SIDES carry `BC_GEOM` on the GENERATED path, measured in check
    14b2 as "one patch name where the shipped document has two". CLOSED for the user
    by #149 rather than removed: naming a far-field geometry is the route to an outlet
    of its own (14f), and the generated path keeps the limitation because that is what
    generating means.
  * **Nothing here writes the far-field geometry for the user.** #133's "the template
    writes no geometry" stands, so the bound path needs a six-segment closed outline
    drawn in the CAD stage, running counter-clockwise from the outlet point level with
    the wake. The refusals name that order; nothing offers to produce it.
  * **The ROTATION refusal rests on the nose being the furthest-upstream joint**, which
    is true of every C-grid far field this repo has and is not a theorem. A far field
    whose leftmost corner is not `f2` is refused by name rather than meshed wrongly,
    which is the safe direction, but it is a refusal the user cannot argue with.
  * The GROWTH constant is this project's own red line for cell expansion rather than a
    derivation. Check 11b measures that it reproduces the shipped document's radial
    count to within two nodes, which is the closest thing to a check on it that exists;
    nothing here says 1.2 is the right number.
  * The `up_first` measurement is exercised on a MIRRORED section, which for a
    symmetric designation is the same shape wound the other way. A cambered section
    drawn clockwise is not in the spread, and the code path is the same one.
  * Check 14c's bound on peak non-orthogonality is a FACTOR against the shipped case's
    own number, so it moves if the shipped case changes. It is a bound on the cost of
    the hexagon, not a quality target.

Run:  python3 tools/PreProcessor/tests/test_topology_cgrid.py
Skips the real-binary half cleanly if ./build/HybMesh2D is not built.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import tempfile

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.abspath(os.path.join(_HERE, "..", "..", ".."))
_BIN = os.path.join(_REPO, "build", "HybMesh2D")
_GUI = os.path.join(_REPO, "tools", "PreProcessor", "gui")
sys.path.insert(0, _GUI)
sys.path.insert(0, _HERE)

import topology_doc_invariants as inv  # noqa: E402
from app.services import topology_binding as tb  # noqa: E402
from app.services import topology_cgrid as cg  # noqa: E402
from app.services import topology_model as tm  # noqa: E402
from app.services import topology_ogrid_binding as _ogb  # noqa: E402
from topology_outline_fixture import (  # noqa: E402
    write_airfoil, write_cgrid_farfield,
)

failures = []


def check(msg, cond):
    print(("PASS " if cond else "FAIL ") + msg)
    if not cond:
        failures.append(msg)


class Cfg:
    """The duck a binding context reads: a geometry list and one length."""

    def __init__(self, geoms, first_cell=1e-3):
        self.geom_files = list(geoms)
        self.bl_initial_thickness = first_cell


def model(geom, **kw):
    return tm.TopologyModel(family=cg.FAMILY, cgrid_body_geom=geom, **kw)


_TMP = tempfile.TemporaryDirectory()
_T = _TMP.name

#: Each fixture is a reason, not a variation.
FIX = {
    # The shipped hand-written C-grid's own section: a sharp NACA 0012 of unit chord
    # at the origin, split at the trailing and leading edges.
    "unit": write_airfoil(os.path.join(_T, "unit"), [0, 1], ["wall", "wall"]),
    # Segment ids that are NOT positions, and two DIFFERENT conditions, so a mesh
    # whose walls came off the wrong segments cannot look right.
    "odd-ids": write_airfoil(os.path.join(_T, "odd"), [7, 3],
                             ["suction", "pressure"]),
    # The same section wound CLOCKWISE: the segment leaving the trailing edge is then
    # the LOWER surface, which the family has to measure rather than assume.
    "mirror": write_airfoil(os.path.join(_T, "mir"), [4, 9], ["suction", "pressure"],
                            mirror_y=True),
    # Cambered, pitched, scaled and moved off the origin, so nothing in the far-field
    # placement can be reading a zero it was handed.
    "cambered": write_airfoil(os.path.join(_T, "cam"), [2, 5], ["wall", "wall"],
                              designation="2412", chord=2.0, x_le=3.0, y_le=-1.0,
                              alpha_deg=5.0),
    # BLUNT: three segments, because that is what the CAD stage draws one as.
    "blunt": write_airfoil(os.path.join(_T, "blunt"), [0, 1, 2],
                           ["wall", "wall", "wall"], sharp_te=False),
    # THE OPTIONALLY DRAWN FAR FIELD (#149), around the "unit" section and cut the
    # way a C-grid binds one: SIX segments, one per block side, running
    # counter-clockwise from the outlet point level with the wake — and with ids
    # that are not positions and two DIFFERENT conditions, which is the whole point
    # of drawing it rather than generating it.
    "far6": write_cgrid_farfield(os.path.join(_T, "ff6"), [5, 2, 9, 4, 1, 8],
                                 ["outlet", "farfield", "farfield", "farfield",
                                  "farfield", "outlet"]),
    # The same outline cut into FIVE, which is a far field segmented for something
    # other than this template, and the refusal is what the user gets.
    "far5": write_cgrid_farfield(os.path.join(_T, "ff5"), [0, 1, 2, 3, 4],
                                 ["outlet"] * 5),
    # ...and into SEVEN, so the refusal is not "fewer than six".
    "far7": write_cgrid_farfield(os.path.join(_T, "ff7"), list(range(7)),
                                 ["outlet"] * 7),
    # Drawn the other way round, and drawn starting at the next joint along: the two
    # arrangements in which every id still resolves and every side still lies on its
    # own segment, so nothing but a measurement can see them.
    "far-cw": write_cgrid_farfield(os.path.join(_T, "ffcw"), [5, 2, 9, 4, 1, 8],
                                   ["outlet"] * 6, cw=True),
    "far-rot": write_cgrid_farfield(os.path.join(_T, "ffrot"), [5, 2, 9, 4, 1, 8],
                                    ["outlet"] * 6, rotate=1),
    # SIX segments and still not a loop: the outlet side stops a quarter short, so
    # the closed-loop refusal is reached by an outline the segment count accepts.
    "far-open": write_cgrid_farfield(os.path.join(_T, "ffopen"), [5, 2, 9, 4, 1, 8],
                                     ["outlet"] * 6, closed=False),
    # THE TWO SHAPES `signed_area` ANSWERS 0.0 FOR, which its own docstring says a
    # caller must tell from a DIRECTION rather than reading one off: a closed
    # six-segment outline enclosing NO AREA, and one with a span of no length. Both
    # were answered "you drew it clockwise, redraw it the other way round" before
    # #149's review, and the no-length refusal below them was unreachable.
    "far-flat": write_cgrid_farfield(os.path.join(_T, "ffflat"), [5, 2, 9, 4, 1, 8],
                                     ["outlet"] * 6, flat=True),
    "far-zero": write_cgrid_farfield(os.path.join(_T, "ffzero"), [5, 2, 9, 4, 1, 8],
                                     ["outlet"] * 6, zero_seg=True),
}

SPREAD = [
    ("the shipped section, on the model's own defaults", "unit", {}),
    ("segment ids that are not positions", "odd-ids", {}),
    ("a section wound CLOCKWISE", "mirror", {}),
    ("cambered, pitched, twice the chord and off the origin", "cambered",
     dict(cgrid_wake_length=38.0, cgrid_far_radius=20.0, cgrid_cell=0.04,
          cgrid_te_cell=0.01)),
    ("both counts overridden", "unit",
     dict(cgrid_wake_count=30, cgrid_radial_count=25)),
    ("a target cell larger than a whole surface", "unit", dict(cgrid_cell=99.0)),
    # #149: the SAME section with its far field DRAWN rather than generated. In the
    # spread rather than in a section of its own, so checks 1-9c — the structural
    # rules, the one cut, the four-way corner and the real-coordinate winding — are
    # asked of the bound document too, which is the whole claim that the second path
    # is a branch and not a second family.
    ("a DRAWN far field, bound over its six segments", "unit",
     dict(cgrid_far_geom=FIX["far6"])),
]


def context(fixname, first_cell=1e-3, extra=()):
    """``(the section's path, a context loading it)`` — plus any far field named.

    The far field is a SECOND geometry of the mesh, exactly as the O-grid's is, so
    a spread entry that binds one has to load it: a context that did not would
    refuse with "not one of this mesh's geometries", which is a real refusal about
    the wrong thing.
    """
    path = FIX[fixname]
    return path, tb.context_for_config(Cfg([path] + list(extra), first_cell))


def spread_context(fixname, kw):
    """The context a SPREAD entry needs, derived from the entry rather than listed."""
    far = kw.get("cgrid_far_geom")
    return context(fixname, extra=[far] if far else ())


_DOCS = []
for _why, _fx, _kw in SPREAD:
    _p, _c = spread_context(_fx, _kw)
    _DOCS.append((_why, tm.build_document(model(_p, **_kw), _c)))

# ── 1-7. the structural rules, from the ONE checker all three family gates call ──
bad = [c for why, d in _DOCS for c in inv.unique_ids(why, d)]
check("1. every corner, edge and block id is unique, across the spread: "
      + (", ".join(bad) if bad else "none duplicated"), not bad)

bad = [c for why, d in _DOCS for c in inv.ring_closes(why, d)]
check("2. every block's four edges close a ring by the MESHER'S own rule — the south "
      "edge fixes the frame and the other three may be declared either way, which is "
      "what a cut shared as the west of two blocks forces: "
      + (", ".join(bad) if bad else "all closed"), not bad)

bad = [c for why, d in _DOCS for c in inv.legal_counts(why, d)]
check("3. every declared count is an integer >= 2: "
      + (", ".join(bad) if bad else "all legal"), not bad)

bad = [c for why, d in _DOCS for c in inv.one_seed_per_class(why, d)]
check("4. exactly one count seed per equivalence class — the five radials are ONE "
      "class and the wake and the two far-field side edges are another, so four seeds "
      "decide twelve edges: "
      + ("; ".join(bad) if bad else "one seed in every class"), not bad)
_classes = {}
for _why, _d in _DOCS[:1]:
    _seeds = [e["id"] for e in _d["edges"] if "count" in e]
check(f"4b. ...and there are exactly FOUR of them, which is what the shipped "
      f"hand-written document declares by hand ({_seeds})", len(_seeds) == 4)

bad = [c for why, d in _DOCS for c in inv.kind_usage(why, d)]
check("5. every 'wall' bounds exactly one block side and every interior line — "
      "'interface' AND 'cut' — exactly two: "
      + (", ".join(bad) if bad else "all as declared"), not bad)

check("6a. all five schema key sets were READ from src/MultiBlock.cpp by a marker "
      f"key rather than assumed ({sorted(inv.SCHEMA)}), so 6b cannot pass vacuously",
      inv.schema_readable())
bad = [c for why, d in _DOCS for c in inv.no_unknown_keys(why, d)]
check("6b. every emitted key is one the mesher's schema accepts: "
      + (", ".join(bad) if bad else "no unknown key"), not bad)

bad = [c for why, d in _DOCS for c in inv.nothing_orphaned(why, d)]
check("7. no corner lies on no edge and no edge lies in no block: "
      + ("; ".join(bad) if bad else "everything reaches something"), not bad)

# ── 8. the two structures this family exists for ───────────────────────────
bad = []
for why, d in _DOCS:
    cuts = [e for e in d["edges"] if e["kind"] == "cut"]
    if len(cuts) != 1:
        bad.append(f"{why}: {len(cuts)} cut edge(s)")
        continue
    cid = cuts[0]["id"]
    wests = [b["id"] for b in d["blocks"] if b["edges"][3] == cid]
    if len(wests) != 2:
        bad.append(f"{why}: the cut is the west of {wests}")
check("8. EXACTLY ONE 'cut' edge, and it is the WEST (index 3 of [south, east, "
      "north, west]) of BOTH wake blocks — not merely an edge two blocks share, "
      "which any interface is: " + ("; ".join(bad) if bad else "one cut, two wests"),
      not bad)
bad = []
for why, d in _DOCS:
    by_e = {e["id"]: e for e in d["edges"]}
    on = {}
    for b in d["blocks"]:
        for cid in {c for eid in b["edges"] for c in by_e[eid]["corners"]}:
            on.setdefault(cid, set()).add(b["id"])
    four = [c for c, bs in on.items() if len(bs) == 4]
    if len(four) != 1:
        bad.append(f"{why}: {len(four)} corner(s) on four blocks")
        continue
    ends = [e["id"] for e in d["edges"] if four[0] in e["corners"]]
    if len(ends) != 5:
        bad.append(f"{why}: {len(ends)} edge(s) end on {four[0]}")
check("8b. ONE declared corner is shared by all FOUR blocks, and FIVE edges end on "
      "it — the cut, the two trailing-edge radials and the two surfaces — so the "
      "highest-risk point in the grid is welded by identity and needs no tolerance: "
      + ("; ".join(bad) if bad else "one four-way corner, five edges"), not bad)
# GUARDED, because a mutation that removes the cut altogether must leave the rest of
# this file RUNNING: an injection that crashes the gate at its third check is measured
# on three checks, and what the other thirty would have said is then unknown.
_cuts = [e for e in _DOCS[0][1]["edges"] if e["kind"] == "cut"]
check(f"8c. ...and the cut carries NO binding, so no face of it reaches the .bnd and "
      f"the two blocks share its nodes by identity rather than coinciding "
      f"({sorted(_cuts[0]) if _cuts else 'there is no cut edge'})",
      bool(_cuts) and "binding" not in _cuts[0])

# ── 9. the section is READ, not assumed ────────────────────────────────────
_up, _cu = context("unit")
_mi, _cm = context("mirror")
_pu, _pm = cg.plan(model(_up), _cu), cg.plan(model(_mi), _cm)
check(f"9. the trailing edge is the joint further DOWNSTREAM and the upper surface is "
      f"the one on the +y side of the chord, both measured: the anticlockwise section "
      f"leaves its trailing edge on segment {_pu.section.up_seg} (upper) and the "
      f"CLOCKWISE one on segment {_pm.section.lo_seg} (lower), so `up_first` is "
      f"{_pu.section.up_first} against {_pm.section.up_first}",
      not _pu.problem and not _pm.problem
      and _pu.section.up_first and not _pm.section.up_first
      and _pu.section.te_seg == 0 and _pm.section.te_seg == 4)
_du = tm.build_document(model(_up), _cu)
_dm = tm.build_document(model(_mi), _cm)


def _edge(doc, eid):
    return [e for e in doc["edges"] if e["id"] == eid][0]


check(f"9b. ...and the ONLY thing that changes is the direction the two surface edges "
      f"are declared in — no mirrored block tuple, because a block's west may be "
      f"declared either way (af_up runs {_edge(_du, 'af_up')['corners']} against "
      f"{_edge(_dm, 'af_up')['corners']})",
      _edge(_du, "af_up")["corners"] == ["te", "le"]
      and _edge(_dm, "af_up")["corners"] == ["le", "te"]
      and [b["edges"] for b in _du["blocks"]] == [b["edges"] for b in _dm["blocks"]])


def ring_area(doc, ctx, block):
    """Twice the signed area of ``block``'s corner ring, from PLACED corners.

    Positive is counter-clockwise, which the mesher's block-orientation rule
    requires. Placed rather than declared: a block whose edges close a ring in the
    declaration can still wind the wrong way round on the page. Walked by the
    MESHER's frame rule, since this family declares edges in either direction.
    """
    by_e = {e["id"]: e for e in doc["edges"]}
    by_c = {c["id"]: c for c in doc["corners"]}
    place = tb.locator(ctx)

    def at(cid):
        c = by_c[cid]
        return place(c) if c["kind"] == "on_geometry" else tuple(c["xy"])

    s, e, n, w = (by_e[i]["corners"] for i in block["edges"])
    a, b = s
    d = inv._other_end(w, a)
    c = inv._other_end(e, b)
    # A ring that does not close has no area rather than a KeyError: check 2 is what
    # reports that, and a crash here would stop this file before it got there.
    if c is None or d is None:
        return 0.0
    pts = [at(x) for x in (a, b, c, d)]
    if any(p is None for p in pts):
        return 0.0
    return sum(pts[k][0] * pts[(k + 1) % 4][1] - pts[(k + 1) % 4][0] * pts[k][1]
               for k in range(4))


bad = []
for why, fixname, kw in SPREAD:
    path, ctx = spread_context(fixname, kw)
    d = tm.build_document(model(path, **kw), ctx)
    for blk in d["blocks"]:
        if ring_area(d, ctx, blk) <= 0.0:
            bad.append(f"{why}/{blk['id']}")
check("9c. every block's corner ring winds COUNTER-CLOCKWISE in real coordinates, on "
      "a clockwise section as well as an anticlockwise one — measured from where the "
      "binding and the generated corners put them, not read off the declaration: "
      + (", ".join(bad) if bad else "all counter-clockwise"), not bad)

# ── 10. a binding is a stable ID, and a broken one refuses ─────────────────
_od, _co = context("odd-ids")
_do = tm.build_document(model(_od), _co)
_binds = {e["id"]: e["binding"]["seg"] for e in _do["edges"] if "binding" in e}
_corner_segs = {c["id"]: c["seg"] for c in _do["corners"] if c["kind"] == "on_geometry"}
check(f"10. the two surface edges bind to the geometry's OWN segment ids and the two "
      f"section corners are declared on them ({_binds}, corners {_corner_segs}) — a "
      f"positional implementation would say 0 and 1 here",
      _binds == {"af_up": 7, "af_lo": 3} and _corner_segs == {"te": 7, "le": 3})
check(f"10b. ...and EVERY edge that is not the section's is a free-cornered far-field "
      f"side with no binding, which is what generating the far field means: "
      f"{sorted(e['id'] for e in _do['edges'] if 'binding' not in e)}",
      {e["id"] for e in _do["edges"] if "binding" in e} == {"af_up", "af_lo"}
      and sum(1 for c in _do["corners"] if c["kind"] == "free") == 6)
_broken = model(_od, cgrid_body_segs="7,99")
_pb = cg.plan(_broken, _co)
_rows = tm.broken_bindings(_broken, _co)
check(f"10c. a stored id the section no longer carries REFUSES and names the edge, "
      f"rather than falling back to the configured default condition: "
      f"{_pb.problem[:90]!r}",
      "no longer has" in _pb.problem and _pb.broken_edge == "af_lo")
check(f"10d. ...and the family reports it as a repairable row naming BOTH surface "
      f"edges, because with one span missing it cannot say which is the upper "
      f"({[(r.field, r.pos, r.seg, r.edges, r.choices) for r in _rows]})",
      len(_rows) == 1 and _rows[0].pos == 1 and _rows[0].seg == 99
      and _rows[0].edges == ("af_up", "af_lo")
      and _rows[0].choices == (7, 3) and _rows[0].field == "cgrid_body_segs")
try:
    tm.build_document(_broken, _co)
    _raised = False
except ValueError:
    _raised = True
check("10e. ...and build_document RAISES rather than returning a document the mesher "
      "would then reject with a message about the document", _raised)

# ── 11. the counts are DERIVED, DISPLAYED and OVERRIDABLE ─────────────────
_p = cg.plan(model(_up), _cu)
_d = tm.build_document(model(_up), _cu)
_seeded = {e["id"]: e["count"] for e in _d["edges"] if "count" in e}
check(f"11. the counts the DOCUMENT seeds are the ones the plan reports, so the panel "
      f"cannot display a figure the mesh does not use ({_seeded} against surfaces "
      f"{_p.up_nodes}/{_p.lo_nodes}, wake {_p.wake_nodes}, radial {_p.radial_nodes})",
      _seeded == {"wake": _p.wake_nodes, "r_te_up": _p.radial_nodes,
                  "af_up": _p.up_nodes, "af_lo": _p.lo_nodes})
_ship_doc = json.loads(re.sub(r"//.*", "", open(
    os.path.join(_REPO, "examples", "topology", "cgrid_naca0012.json"),
    encoding="utf-8").read()))
_ship_rad = [e["count"] for e in _ship_doc["edges"] if e["id"] == "r_te_up"][0]
check(f"11b. the radial derivation — a law starting at the run's "
      f"BL_INITIAL_THICKNESS and never growing faster than {cg.GROWTH}, which is this "
      f"project's own red line for cell expansion — lands within two nodes of the "
      f"count the shipped hand-written document declares by hand "
      f"({_p.radial_derived} against {_ship_rad})",
      abs(_p.radial_derived - _ship_rad) <= 2)
_ov = cg.plan(model(_up, cgrid_wake_count=30, cgrid_radial_count=25), _cu)
check(f"11c. the derivation is a DEFAULT and not a cage: overrides of 30 and 25 are "
      f"taken and reported as overrides, with the derived counts still stated "
      f"(got {_ov.wake_nodes}/{_ov.radial_nodes}, derived "
      f"{_ov.wake_derived}/{_ov.radial_derived})",
      _ov.wake_nodes == 30 and _ov.radial_nodes == 25 and _ov.wake_overridden
      and _ov.radial_overridden and _ov.wake_derived == _p.wake_derived
      and _ov.radial_derived == _p.radial_derived)
_no_run = cg.plan(model(_up), tb.context_for_config(Cfg([_up], first_cell=0.0)))
check(f"11e. a run that declares no BL_INITIAL_THICKNESS still derives a radial "
      f"count, from the trailing-edge cell — and the read-out NAMES that source "
      f"rather than printing one parameter under another's name "
      f"({_no_run.lines()[3]!r})",
      not _no_run.problem and not _no_run.first_cell_from_run
      and "BL_INITIAL_THICKNESS" not in _no_run.lines()[3].split("—")[0]
      and "trailing-edge cell" in _no_run.lines()[3]
      and _p.first_cell_from_run)
_lines = _p.lines()
check(f"11d. ...and the read-out shows the WORKING rather than only the result — the "
      f"section as it was read, the spacing and the growth each count came from, and "
      f"the far field's own limitation: {_lines!r}",
      len(_lines) == 5
      and any("chord" in ln and "trailing edge at" in ln for ln in _lines)
      and any("BL_INITIAL_THICKNESS" in ln for ln in _lines)
      and any(str(cg.GROWTH) in ln for ln in _lines)
      and any("BC_GEOM" in ln for ln in _lines))

# ── 12. a blunt trailing edge is refused, with a sharp one as the control ──
_bl, _cb = context("blunt")
_pbl = cg.plan(model(_bl), _cb)
check(f"12. a BLUNT trailing edge is refused with the problem NAMED — the section has "
      f"a base segment of its own and its two surfaces never meet, so there is no "
      f"single corner for the four blocks to share: {_pbl.problem[:140]!r}",
      bool(_pbl.problem) and "BLUNT" in _pbl.problem
      and "Sharp trailing edge" in _pbl.problem)
check("12b. ...with the SHARP section of the same designation as the negative "
      "control, which is refused for nothing", not cg.plan(model(_up), _cu).problem)
_cases = [
    ("no geometry named at all", model(""), _cu, "name the aerofoil geometry"),
    ("a geometry this mesh does not load",
     model(os.path.join(_T, "never_drawn.dat")), _cu,
     "not one of this mesh's geometries"),
    ("a far field that does not contain the section",
     model(_up, cgrid_far_radius=0.02), _cu, "outside the far field"),
    ("a wake length of zero", model(_up, cgrid_wake_length=0.0), _cu,
     "wake length must be greater than zero"),
    ("a target cell edge of zero", model(_up, cgrid_cell=0.0), _cu,
     "target cell edge must be greater than zero"),
    ("a binding token that is not a segment id",
     model(_up, cgrid_body_segs="0,x"), _cu, "is not a segment id"),
    ("a binding naming one segment twice", model(_up, cgrid_body_segs="0,0"), _cu,
     "twice"),
    ("no context at all", model(_up), None,
     "it needs the mesh's geometry list"),
]
bad = []
for why, mm, cc, want in _cases:
    got = cg.plan(mm, cc).problem or ""
    if want not in got:
        bad.append(f"{why}: got {got[:80]!r}")
check("12c. each refusable configuration is refused with a sentence naming the fix "
      "rather than with a bare failure: "
      + ("; ".join(bad) if bad else f"all {len(_cases)} named"), not bad)

# ── 13. the generated far field lands on the shipped document's own corners ─
_SHIP_AF = os.path.join(_REPO, "examples", "geometries", "naca0012_cgrid.dat")
_SHIP_FF = os.path.join(_REPO, "examples", "geometries", "cgrid_farfield.dat")
_ship_ctx = tb.context_for_config(Cfg([_SHIP_AF, _SHIP_FF]))
_place = tb.locator(_ship_ctx)
_ship_far = {c["id"]: _place(c) for c in _ship_doc["corners"]
             if c["geom"].endswith("cgrid_farfield.dat")}
_tpl = cg.plan(model(_SHIP_AF), tb.context_for_config(Cfg([_SHIP_AF])))
_off = {k: max(abs(_tpl.far[k][0] - _ship_far[k][0]),
               abs(_tpl.far[k][1] - _ship_far[k][1])) for k in _ship_far}
check(f"13. on the model's UNTOUCHED defaults the six generated far-field corners "
      f"land EXACTLY where the shipped hand-written document's own six are, so "
      f"'reproduces the target' is a comparison rather than a resemblance "
      f"(worst offset {max(_off.values()):.3e}; {_off})",
      set(_off) == {"wk", "fu", "f1", "f2", "f3", "fl"}
      and max(_off.values()) < 1e-9)
_def = tm.TopologyModel()
check(f"13b. ...and those really are the untouched defaults (wake "
      f"{_def.cgrid_wake_length}, radius {_def.cgrid_far_radius}, cell "
      f"{_def.cgrid_cell}, te cell {_def.cgrid_te_cell}, overrides "
      f"{_def.cgrid_wake_count}/{_def.cgrid_radial_count})",
      (_def.cgrid_wake_length, _def.cgrid_far_radius, _def.cgrid_cell,
       _def.cgrid_te_cell, _def.cgrid_wake_count, _def.cgrid_radial_count)
      == (19.0, 10.0, 0.02, 0.005, 0, 0))

# ── 18. the far field is OPTIONALLY DRAWN (#149) ──────────────────────────
# The SECOND of the two paths, and the one the shipped hand-written document has
# always been on. Nothing here is a new mechanism: the binding, the capture, the
# refusal and the repair are #137's and #138's, and the O-grid already drives every
# one of them for a far field specifically. What is measured is the branch.
from app.services import topology_cgrid_section as cs  # noqa: E402

_f6, _cf = context("unit", extra=[FIX["far6"]])
_bound = model(_f6, cgrid_far_geom=FIX["far6"])
_pf = cg.plan(_bound, _cf)
_df = tm.build_document(_bound, _cf)
_gen = cg.plan(model(_up), _cu)
check(f"18. BLANK IS THE DEFAULT AND IS NOT A DEGRADED STATE: a fresh model names no "
      f"far-field geometry, so the far field is GENERATED and its six corners belong "
      f"to no geometry (far_bound {_gen.far_bound}, free corners "
      f"{sum(1 for c in _du['corners'] if c['kind'] == 'free')}, bound far edges "
      f"{[e['id'] for e in _du['edges'] if 'binding' in e]})",
      not tm.TopologyModel().cgrid_far_geom and not _gen.far_bound
      and sum(1 for c in _du["corners"] if c["kind"] == "free") == 6
      and [e["id"] for e in _du["edges"] if "binding" in e] == list(cs.SURFACE_EDGES))
_fcorners = {c["id"]: c["seg"] for c in _df["corners"] if c["kind"] == "on_geometry"}
_fbinds = {e["id"]: e["binding"]["seg"] for e in _df["edges"] if "binding" in e}
# GUARDED with `.get`, by this file's own rule: a mutation that stops the far field
# binding at all leaves `far_segs` EMPTY, and a `_want[c]` would then raise inside
# check 18b and take every check after it with it — measured as one bite where the
# truth is several (injection K).
_want = dict(zip(cs.FAR_CORNERS, _pf.far_segs))
check(f"18b. ...and naming a six-segment far field turns those six corners into "
      f"corners OF IT and binds the six sides to its own segment ids, one side per "
      f"segment, in the order the block sides run ({_fcorners}, edges {_fbinds}) — "
      f"ids of 5, 2, 9, 4, 1, 8, so a positional implementation would say 0 to 5",
      not _pf.problem and _pf.far_bound
      and _pf.far_segs == (5, 2, 9, 4, 1, 8)
      and all(_fcorners.get(c) == _want.get(c) is not None
              for c in cs.FAR_CORNERS)
      and all(_fbinds.get(e) == _want.get(c)
              for e, c in zip(cs.FAR_EDGES, cs.FAR_CORNERS))
      and set(_fbinds) == set(cs.FAR_EDGES) | set(cs.SURFACE_EDGES)
      and not [c for c in _df["corners"] if c["kind"] == "free"])
# GUARDED for the reason 8c and 18b are: under a mutation that stops the far field
# binding, these two absurd lengths become LIVE, the containment check refuses, and
# an unguarded `build_document` would take the whole file down with it — a bite
# measured on one check where the truth is several (injection K).
try:
    _inert = tm.build_document(
        model(_f6, cgrid_far_geom=FIX["far6"], cgrid_wake_length=999.0,
              cgrid_far_radius=0.001), _cf)
except ValueError as _exc:
    _inert = f"refused: {_exc}"
_last = _pf.lines()[-1]
check(f"18c. ...at which point the wake length and the far-field radius decide "
      f"NOTHING — a 999 wake and a 0.001 radius project the IDENTICAL document — and "
      f"the read-out SAYS so rather than leaving two live controls looking live "
      f"({_last!r})",
      _inert == _df and "INERT" in _last and "BOUND" in _last
      and os.path.basename(FIX["far6"]) in _last)
check(f"18c2. ...and the spans the two counts are derived from come off the DRAWN "
      f"geometry rather than off the inert parameters: the wake spans "
      f"{_pf.wake_span:.4g} and the radial {_pf.radial_span:.4g}, which is where the "
      f"far field was drawn, and the generated path still reads its parameters "
      f"({_gen.wake_span:.4g} / {_gen.radial_span:.4g})",
      abs(_pf.wake_span - 19.0) < 1e-9 and abs(_pf.radial_span - 10.0) < 1e-9
      and "BC_GEOM" in _gen.lines()[-1] and "INERT" not in _gen.lines()[-1])
_ffg = _cf.geometry(FIX["far6"])


def poly_area(ring):
    """Twice the enclosed area of a closed polygon, by the shoelace."""
    return abs(sum(ring[k][0] * ring[(k + 1) % len(ring)][1]
                   - ring[(k + 1) % len(ring)][0] * ring[k][1]
                   for k in range(len(ring))))


# The geometry's OWN segment list rather than the plan's, so a mutation that leaves
# `far_segs` empty cannot divide by a zero area here and take the file down (the
# guarding rule 8c, 18b and 18c already follow).
_chord_ring = [_ffg.spans[sid].point_at(0.0) for sid in _ffg.seg_ids]
_drawn = cs.drawn_ring(_ffg)
check(f"18c3. ...and the containment refusal tests the DRAWN outline, not the six "
      f"corner chords, which is the whole difference between the two paths: a "
      f"generated hexagon's sides ARE its chords, while a drawn D curves OUTWARD "
      f"between its joints, so the region the drawn ring encloses is STRICTLY LARGER "
      f"({poly_area(_drawn) / poly_area(_chord_ring):.4f}x over "
      f"{len(_drawn)} points against {len(_chord_ring)}). Testing containment on the "
      f"chords would refuse a section that sits comfortably inside the shape the "
      f"user actually drew",
      len(_drawn) > len(_chord_ring)
      and poly_area(_drawn) > poly_area(_chord_ring) * 1.01)

_bad_counts = []
for _why, _fx in (("five", "far5"), ("seven", "far7")):
    _pc, _cc = context("unit", extra=[FIX[_fx]])
    _why2 = cg.plan(model(_pc, cgrid_far_geom=FIX[_fx]), _cc).problem or ""
    if "exactly 6 segments" not in _why2 or "one per block side" not in _why2:
        _bad_counts.append(f"{_why}: {_why2[:80]!r}")
check("18d. a far field cut into other than SIX segments is refused by name — one "
      "segment per block side is what makes each side's condition readable off its "
      "own — with the six-segment outline as the negative control: "
      + ("; ".join(_bad_counts) if _bad_counts else "five and seven both refused"),
      not _bad_counts and not _pf.problem)


def invisible_to_bindings(fixname):
    """Every BINDING question answered YES about the far field ``fixname``.

    The claim 18e and 18f rest on, ASSERTED rather than asserted-about: under both
    of those outlines every stored id resolves, every side lies on its own segment
    and the list walks the outline's own order — so the four checks this package
    already had all pass, and only the new measurement refuses. A label saying
    "nothing but a measurement could see it" and an assert grepping a sentence are
    not the same statement; this is the gap between them.
    """
    path, ctx = context("unit", extra=[FIX[fixname]])
    g = ctx.geometry(FIX[fixname])
    held, why, edge = cs.held_bindings(ctx, g, "", cs.FAR_ROLE, cs.far_edge_at)
    order = cs.order_problem(cs.FAR_ROLE, g, held, 1, cs.far_edge_at)[1]
    cover = _ogb.cover_problem(cs.FAR_ROLE, g, held, 1, cs.far_edge_at)[1]
    return (path, ctx, len(held) == cs.FAR_SEGMENTS and not why and not edge
            and not order and not cover)


_pw, _cw2, _blind_cw = invisible_to_bindings("far-cw")
_why_cw = cg.plan(model(_pw, cgrid_far_geom=FIX["far-cw"]), _cw2).problem or ""
check(f"18e. a far field drawn the OTHER WAY ROUND is refused, and nothing but a "
      f"measurement could see it — every id resolves, every side lies on its own "
      f"segment and the list walks the outline's own order, so parse, resolve, "
      f"order and cover all pass ({_blind_cw}) and the mesher would answer with a "
      f"folded grid rather than a refusal ({_why_cw[:110]!r})",
      _blind_cw and "CLOCKWISE" in _why_cw and "other direction" in _why_cw)
_pr, _cr, _blind_rot = invisible_to_bindings("far-rot")
_why_rot = cg.plan(model(_pr, cgrid_far_geom=FIX["far-rot"]), _cr).problem or ""
check(f"18f. ...and so is one drawn STARTING AT THE NEXT JOINT ALONG, invisible to "
      f"the same four ({_blind_rot}): the refusal names where the nose corner has to "
      f"sit and which order the six sides run in ({_why_rot[:140]!r})",
      _blind_rot and "furthest-upstream corner" in _why_rot
      and f"position {cs.FAR_NOSE_POS}" in _why_rot
      and cs.FAR_EDGES[0] in _why_rot)
_degen = []
for _why, _fx, _want in (
        ("a closed six-segment outline enclosing NO AREA", "far-flat",
         "enclose no area"),
        ("one of whose spans has no length", "far-zero",
         "has a segment with no length")):
    _pd, _cd = context("unit", extra=[FIX[_fx]])
    _gd = cg.plan(model(_pd, cgrid_far_geom=FIX[_fx]), _cd).problem or ""
    if _want not in _gd:
        _degen.append(f"{_why}: got {_gd[:90]!r}")
check("18f2. a far field `signed_area` answers 0.0 for is refused for WHAT IT IS, "
      "not read as a DIRECTION — its own docstring says a caller must report that "
      "as a refusal rather than a winding, and both of these were told to 'redraw "
      "the far field in the other direction' until the corners were placed before "
      "the ring was measured: "
      + ("; ".join(_degen) if _degen else "both named for what they are"),
      not _degen)

_brk = model(_f6, cgrid_far_geom=FIX["far6"], cgrid_far_segs="5, 2, 9, 4, 1, 99")
_pbf = cg.plan(_brk, _cf)
_rowsf = tm.broken_bindings(_brk, _cf)
check(f"18g. a stored far-field id the geometry no longer carries REFUSES with the "
      f"EDGE named, exactly as the section's does ({_pbf.problem[:80]!r}, edge "
      f"{_pbf.broken_edge!r})",
      "no longer has" in _pbf.problem and _pbf.broken_edge == cs.FAR_EDGES[5])
check(f"18h. ...and the family reports it as a repairable row naming ONE edge — on "
      f"the far field the position IS the side, where on the section it is not "
      f"({[(r.field, r.who, r.pos, r.seg, r.edges, r.choices) for r in _rowsf]})",
      len(_rowsf) == 1 and _rowsf[0].field == "cgrid_far_segs"
      and _rowsf[0].who == cs.FAR_ROLE and _rowsf[0].pos == 5
      and _rowsf[0].seg == 99 and _rowsf[0].edges == (cs.FAR_EDGES[5],)
      and _rowsf[0].choices == (5, 2, 9, 4, 1, 8))
check("18h2. ...and the repair is the O-grid's ROTATION, unchanged: naming the "
      "segment that side should lie on rewrites the whole list, because where the "
      "ring starts is the only freedom a valid one has",
      _ogb.repair_binding((5, 2, 9, 4, 1, 8), 5, 8) == "5, 2, 9, 4, 1, 8"
      and not cg.plan(model(_f6, cgrid_far_geom=FIX["far6"],
                            cgrid_far_segs=_ogb.repair_binding(
                                (5, 2, 9, 4, 1, 8), 5, 8)), _cf).problem)
_fcases = [
    ("a far field this mesh does not load",
     model(_f6, cgrid_far_geom=os.path.join(_T, "never_drawn_ff.dat")), _cf,
     "not one of this mesh's geometries"),
    ("a far field cut into six but not CLOSED", model(_f6,
                                                     cgrid_far_geom=FIX["far-open"]),
     context("unit", extra=[FIX["far-open"]])[1], "is not a closed loop"),
    ("a far field that is not the shape at all (the section itself)",
     model(_f6, cgrid_far_geom=_f6), _cf, "exactly 6 segments"),
    ("a binding token that is not a segment id",
     model(_f6, cgrid_far_geom=FIX["far6"], cgrid_far_segs="5,x"), _cf,
     "is not a segment id"),
    ("a binding naming one segment twice",
     model(_f6, cgrid_far_geom=FIX["far6"], cgrid_far_segs="5,5"), _cf, "twice"),
    ("a binding that does not name all six",
     model(_f6, cgrid_far_geom=FIX["far6"], cgrid_far_segs="5, 2, 9"), _cf,
     "binds ALL 6 sides"),
]
_fbad = []
for _why, _mm, _cc, _want2 in _fcases:
    _got = cg.plan(_mm, _cc).problem or ""
    if _want2 not in _got:
        _fbad.append(f"{_why}: got {_got[:80]!r}")
check("18i. each refusable far-field configuration is refused with a sentence naming "
      "the fix rather than with a bare failure: "
      + ("; ".join(_fbad) if _fbad else f"all {len(_fcases)} named"), not _fbad)
# ── 14. the REAL mesher, and the comparison with the shipped document ──────


def run_mesher(tmp, topo_path, geoms, tag, bc="farfield"):
    conf = os.path.join(tmp, tag + ".dat")
    stem = os.path.join(tmp, tag)
    with open(conf, "w", encoding="utf-8") as fh:
        fh.write("MESH_MODE 1\n"
                 f"MESH_TOPOLOGY_FILE {topo_path}\n"
                 + "".join(f"GEOM_FILE {g}\n" for g in geoms)
                 + "BL_INITIAL_THICKNESS 0.001\nMB_SPLIT_QUADS 1\n"
                   "EXPORT_VTK 1\nEXPORT_STARCD 1\n"
                 f"BC_GEOM {bc}\nOUTPUT_FILENAME {stem}.vtk\n")
    env = dict(os.environ)
    lib = subprocess.run(["bash", os.path.join(_REPO, "tools", "scripts",
                                               "gmsh_lib_dir.sh")],
                         capture_output=True, text=True)
    if lib.returncode == 0 and lib.stdout.strip():
        env["DYLD_LIBRARY_PATH"] = lib.stdout.strip()
    r = subprocess.run([_BIN, "-conf", conf], cwd=tmp, env=env, capture_output=True,
                       text=True, timeout=900)
    out = (r.stdout or "") + (r.stderr or "")
    rows = [ln for ln in out.splitlines() if ln.startswith("HYBMESH_MB_QUALITY ")]
    q = dict(kv.split("=") for kv in rows[-1].split()[1:]) if rows else {}
    names = []
    if os.path.exists(stem + ".bnd"):
        with open(stem + ".bnd", encoding="utf-8") as fh:
            names = sorted({ln.split()[-1] for ln in fh if ln.split()})
    return r.returncode, q, names, out


if not os.path.exists(_BIN):
    print("SKIP  build/HybMesh2D not built; the real-binary half is not measured.")
else:
    with tempfile.TemporaryDirectory() as tmp:
        # THE MODEL'S OWN DEFAULTS on a shipped-style section, which is what
        # "generating from defaults" means; only the geometry is named.
        _m = tm.TopologyModel(family=cg.FAMILY, cgrid_body_geom=_SHIP_AF)
        _topo = tm.project(_m, os.path.join(tmp, "tpl.dat"),
                           tb.context_for_config(Cfg([_SHIP_AF])))
        rc, q, names, out = run_mesher(tmp, _topo, [_SHIP_AF], "tpl")
        check(f"14. the C-grid's DEFAULTS on a drawn aerofoil run the real mesher to "
              f"exit 0 (got {rc})", rc == 0)
        check(f"14a. ...with zero inverted cells, over a mesh that exists "
              f"(inverted {q.get('inverted')} of {q.get('cells')})",
              q.get("inverted") == "0" and int(q.get("cells", 0)) > 0)
        # THE EXPORTED MESH'S BLOCK, not the run's first: the mesher prints the
        # quality twice, before and after the elliptic sweeps, and the two answer
        # different questions here. Everything after the BEFORE block's own machine
        # row is the mesh that was written.
        pre, _, post = out.partition("HYBMESH_MB_QUALITY_BEFORE")
        pat = r"west 'af_(?:up|lo)'\s*:.*?\(([0-9.]+)%\)"
        wf = re.findall(pat, post or pre)
        raw = re.findall(pat, pre) if post else []
        check(f"14b. ...and the first cell at the SECTION's own wall, in the mesh that "
              f"was EXPORTED, is the run's BL_INITIAL_THICKNESS to the percentages "
              f"the mesher itself reports ({wf}) — where the algebraic grid before "
              f"the elliptic sweeps was {raw} off it, because the generated hexagon "
              f"is nearer the section at mid-chord than at the nose and the first "
              f"cell scales with the local i-line. The wall control functions are "
              f"what recover it",
              len(wf) == 2 and all(float(v) < 1.0 for v in wf)
              and len(raw) == 2 and all(float(v) > 1.0 for v in raw))
        check(f"14b2. ...while the six GENERATED far-field sides carry the config's "
              f"BC_GEOM, because a free corner belongs to no geometry — the .bnd "
              f"names {names}, one name where the shipped document has two",
              names == ["farfield", "wall"])

        # THE SHIPPED HAND-WRITTEN DOCUMENT, through the same binary, so the
        # comparison is measured rather than asserted.
        srcs = os.path.join(_REPO, "examples", "topology", "cgrid_naca0012.json")
        rc2, q2, names2, _ship_out = run_mesher(tmp, srcs, [_SHIP_AF, _SHIP_FF],
                                                "ship")
        ratio = (float(q["nonortho_max_deg"]) / float(q2["nonortho_max_deg"])
                 if q.get("nonortho_max_deg") and q2.get("nonortho_max_deg") else 0.0)
        cells = (int(q["cells"]) / int(q2["cells"])
                 if q.get("cells") and q2.get("cells") else 0.0)
        check(f"14c. the mesh the template produces is COMPARED with the shipped "
              f"hand-written C-grid's, not merely declared to reproduce it: template "
              f"{q.get('cells')} cells / {q.get('nonortho_max_deg')} deg peak "
              f"non-orthogonality against shipped {q2.get('cells')} / "
              f"{q2.get('nonortho_max_deg')}, i.e. {cells:.2f}x the cells at "
              f"{ratio:.2f}x the peak. The difference is the far field: a generated "
              f"hexagon where the drawn one curves, which costs at that one corner "
              f"and nothing at the wall",
              rc2 == 0 and q2.get("inverted") == "0" and 0.0 < ratio < 2.0
              and 0.5 < cells < 2.0)

        # THE COMPARISON WHERE IT MATTERS. Peak non-orthogonality and a cell count
        # are whole-mesh figures, and both are dominated by the far field — which is
        # the half these two documents deliberately disagree about. What "reproduces
        # the target" has to mean is the grid AROUND THE SECTION, so this compares the
        # two runs' per-block cell-shape medians for the two body blocks, which the
        # mesher reports itself. Added by #148's Spec review, which read 14c's assert
        # against its own label and found the discretisation ungated.
        def by_block(text):
            tail = text.partition("HYBMESH_MB_QUALITY_BEFORE")[2] or text
            return {m[0]: float(m[1]) for m in re.findall(
                r"block '(\w+)'\s*:\s*median ([0-9.]+)", tail)}

        _t, _s2 = by_block(out), by_block(_ship_out)
        _body = {b: (_t.get(b), _s2.get(b)) for b in ("b_upper", "b_lower")}
        _worst = max((max(a, b) / min(a, b)) for a, b in _body.values()
                     if a and b) if all(all(v) for v in _body.values()) else 0.0
        check(f"14c2. ...and AT THE SECTION the two grids are the same grid: the "
              f"mesher's own per-block cell-shape medians for the two body blocks "
              f"agree to {_worst:.3f}x ({_body}). The whole-mesh figures above are "
              f"dominated by the far field, which is the half the two documents "
              f"deliberately disagree about",
              bool(_worst) and _worst < 1.2)
        check(f"14d. ...and the shipped document's own DRAWN far field is what "
              f"carries the second boundary name the GENERATED path cannot "
              f"({names2} against {names}). #149 is the template learning to bind "
              f"one too, which is 14f below",
              names2 == ["farfield", "outlet", "wall"])

        # THE DRAWN FAR FIELD (#149), on the SAME section and the SAME binary, so
        # what the second path buys is measured against the first rather than
        # asserted. The far field is the shipped hand-written document's own
        # geometry, which is what makes 14g a comparison of like with like.
        _mb = tm.TopologyModel(family=cg.FAMILY, cgrid_body_geom=_SHIP_AF,
                               cgrid_far_geom=_SHIP_FF)
        _topo_b = tm.project(_mb, os.path.join(tmp, "bound.dat"),
                             tb.context_for_config(Cfg([_SHIP_AF, _SHIP_FF])))
        rcb, qb, namesb, outb = run_mesher(tmp, _topo_b, [_SHIP_AF, _SHIP_FF],
                                           "bound")
        check(f"14f. naming a far-field geometry makes the template export the SAME "
              f"THREE boundary names the shipped hand-written document does "
              f"({namesb}) — where the generated path exports {names}, because a "
              f"free corner belongs to no geometry and its sides can only carry "
              f"BC_GEOM. That is the difference between a grid you can look at and "
              f"a grid you can solve on (exit {rcb}, inverted "
              f"{qb.get('inverted')} of {qb.get('cells')})",
              rcb == 0 and qb.get("inverted") == "0"
              and int(qb.get("cells", 0)) > 0 and namesb == names2
              and namesb == ["farfield", "outlet", "wall"])
        _rb = (float(qb["nonortho_max_deg"]) / float(q2["nonortho_max_deg"])
               if qb.get("nonortho_max_deg") and q2.get("nonortho_max_deg") else 0.0)
        _cb = (int(qb["cells"]) / int(q2["cells"])
               if qb.get("cells") and q2.get("cells") else 0.0)
        check(f"14g. ...and the peak non-orthogonality the hexagon cost is GONE, "
              f"because the corner is gone: bound {qb.get('nonortho_max_deg')} deg "
              f"against shipped {q2.get('nonortho_max_deg')} is {_rb:.2f}x, where "
              f"the GENERATED path is {ratio:.2f}x. The CELL COUNT does not move "
              f"between the two paths ({qb.get('cells')} either way, {_cb:.2f}x the "
              f"shipped document's {q2.get('cells')}) — which is the useful half of "
              f"the reading: what 14c measured as '1.28x the cells at 1.63x the "
              f"peak' was two different causes, and only the second was the far "
              f"field. The counts are this family's own derivation and #149 does "
              f"not touch them",
              0.0 < _rb < 1.2 and _rb < ratio
              and qb.get("cells") == q.get("cells") and _cb == cells)
        _tb2 = by_block(outb)
        _bodyb = {b: (_tb2.get(b), _s2.get(b)) for b in ("b_upper", "b_lower")}
        _worstb = max((max(a, b) / min(a, b)) for a, b in _bodyb.values()
                      if a and b) if all(all(v) for v in _bodyb.values()) else 0.0
        check(f"14h. ...and AT THE SECTION the bound grid is still the shipped grid, "
              f"by the same per-block cell-shape medians 14c2 uses "
              f"({_worstb:.3f}x, {_bodyb}) — so the second path changes the boundary "
              f"names and the outer shape without moving the grid the user came for",
              bool(_worstb) and _worstb < 1.2)
        # ALL FOUR BLOCKS, which is where #149's own Testing Decision said "this
        # time the far field should agree too" — and the measurement says NO, so the
        # prediction is CORRECTED here rather than quietly dropped. The two WAKE
        # blocks come out IDENTICAL on the two template paths, because their far side
        # is the outlet plane and the generated hexagon puts it exactly where the
        # drawn D does; they sit off the shipped document by the WAKE NODE COUNT,
        # which is this family's derivation and not the far field. The two BODY
        # blocks move by 3% between the paths and end up NO CLOSER to the shipped
        # grid than the generated path already was. So the per-block cell-shape
        # median is BLIND to what drawing the far field changed; 14g's peak
        # non-orthogonality is the figure that sees it.
        _allb = {b: (_tb2.get(b), _t.get(b), _s2.get(b))
                 for b in ("b_upper", "b_lower", "b_wake_up", "b_wake_lo")}
        _wake_same = all(v[0] == v[1] for b, v in _allb.items()
                         if b.startswith("b_wake"))
        _wake_gap = max((max(v[0], v[2]) / min(v[0], v[2]))
                        for b, v in _allb.items() if b.startswith("b_wake"))
        _body_b = max((max(v[0], v[2]) / min(v[0], v[2]))
                      for b, v in _allb.items() if b.startswith("b_") 
                      and not b.startswith("b_wake"))
        _body_g = max((max(v[1], v[2]) / min(v[1], v[2]))
                      for b, v in _allb.items() if b.startswith("b_")
                      and not b.startswith("b_wake"))
        check(f"14h2. ...but over ALL FOUR blocks this ticket's own prediction that "
              f"'the far field should agree too' is measured FALSE, and that is "
              f"recorded rather than dropped: the two WAKE blocks are IDENTICAL on "
              f"the two template paths ({_wake_same} — their far side is the outlet "
              f"plane, which both documents put in the same place) and sit "
              f"{_wake_gap:.3f}x off the shipped document's because of the WAKE NODE "
              f"COUNT, while the two BODY blocks end up NO CLOSER to it bound "
              f"({_body_b:.3f}x) than generated ({_body_g:.3f}x). The per-block "
              f"cell-shape median cannot see what drawing the far field changed; "
              f"14g's peak non-orthogonality is the figure that can ({_allb}, "
              f"bound/generated/shipped)",
              len(_allb) == 4 and all(all(v) for v in _allb.values())
              and _wake_same and 1.1 < _wake_gap < 1.2
              and abs(_body_b - _body_g) < 0.01)

        # The section's own conditions really do come off its segments.
        rc3, q3, names3, _ = run_mesher(
            tmp, tm.project(model(FIX["odd-ids"]), os.path.join(tmp, "odd.dat"),
                            tb.context_for_config(Cfg([FIX["odd-ids"]]))),
            [FIX["odd-ids"]], "odd", bc="farfield")
        check(f"14e. a section whose two surfaces carry DIFFERENT conditions exports "
              f"them both, read off its own CAD segments rather than from the config "
              f"default ({names3}); BC_GEOM said 'farfield', which is only the "
              f"generated far field's",
              rc3 == 0 and names3 == ["farfield", "pressure", "suction"])

# ── 16. the skeleton, the cut included — and detach/re-attach ─────────────
# Through the REAL MeshConfig and the real services, because #136's own criterion is
# about what the canvas is handed rather than about a document: the mixin asks
# `skeleton_for_config(self.mesh_config)` and nothing else.
from app.models.mesh_config import MeshConfig  # noqa: E402
from app.services import topology_detach, topology_skeleton  # noqa: E402
from app.services.mesh_modes import MESH_MODE_MULTIBLOCK  # noqa: E402

_mc = MeshConfig()
_mc.mesh_mode = MESH_MODE_MULTIBLOCK
_mc.add_geom_file(FIX["unit"])
_mc.bl_initial_thickness = 1e-3
_mc.topology = model(FIX["unit"])
_skel = topology_skeleton.skeleton_for_config(_mc)
_unplaced = [c.id for c in (_skel.corners if _skel else ()) if c.xy is None]
_bound = sorted(c.id for c in (_skel.corners if _skel else ()) if c.bound)
check(f"16. the canvas is handed a skeleton for a C-grid case, with every corner "
      f"PLACED — the two on the section by its binding and the six generated ones by "
      f"their own coordinates (bound {_bound}, unplaced {_unplaced})",
      _skel is not None and len(_skel.corners) == 8 and not _unplaced
      and _bound == ["le", "te"])
_wake = [e for e in _skel.edges if e.id == "wake"][0] if _skel else None
check(f"16b. ...and the WAKE CUT is drawn: it has both endpoints, it is an INTERIOR "
      f"edge rather than a boundary (the two the overlay styles apart), and its count "
      f"is the one the plan derived (xy={_wake.xy is not None}, "
      f"is_boundary={_wake.is_boundary}, label={_wake.label!r})",
      _wake is not None and _wake.xy is not None and not _wake.is_boundary
      and _wake.label == str(_p.wake_nodes) and _wake.declared)
_prop = {e.id: e.count for e in _skel.edges if not e.declared}
check(f"16c. ...and the four seeds PROPAGATE to the other eight edges, so the overlay "
      f"shows the counts the user never typed ({_prop})",
      len(_prop) == 8 and all(v is not None for v in _prop.values())
      and _prop["r_le"] == _p.radial_nodes and _prop["e_out_up"] == _p.radial_nodes
      and _prop["e_ff_up"] == _p.wake_nodes
      and _prop["e_ff_nose_up"] == _p.up_nodes)
with tempfile.TemporaryDirectory() as _dt:
    _out = topology_detach.detach(_mc.topology, _mc, os.path.join(_dt, "hand.json"),
                                  tb.context_for_config(_mc))
    _written = json.load(open(_out, encoding="utf-8"))
    check(f"17. detaching a C-grid writes the document it was projecting and turns "
          f"the family off in one flag — the file has "
          f"{len(_written['blocks'])} blocks and {len(_written['corners'])} corners, "
          f"names_a_family={_mc.topology.names_a_family()}, "
          f"is_detached={_mc.topology.is_detached()}, "
          f"mesh_topology_file={bool(_mc.mesh_topology_file)}",
          len(_written["blocks"]) == 4 and len(_written["corners"]) == 8
          and not _mc.topology.names_a_family() and _mc.topology.is_detached()
          and bool(_mc.mesh_topology_file))
    check("17b. ...so the canvas stops drawing a model the run no longer reads, and "
          "the family reports no broken binding for it",
          topology_skeleton.skeleton_for_config(_mc) is None
          and tm.broken_bindings(_mc.topology,
                                 tb.context_for_config(_mc)) == ())
    _sum = topology_detach.summary(_mc.topology, _mc)
    check(f"17c. ...and the provenance summary names the family AND the quantity the "
          f"family reads from the RUN rather than from the model, which no prefix "
          f"could find: {_sum[:120]!r}",
          "C-grid" in _sum and "BL_INITIAL_THICKNESS" in _sum
          and "Wake Length" in _sum)
    topology_detach.reattach(_mc.topology, _mc)
    check(f"17d. ...and re-attaching puts it back: the family drives the run again "
          f"and the path row is CLEARED, so it cannot decide something while the "
          f"funnel overrides it (file={_mc.mesh_topology_file!r})",
          _mc.topology.names_a_family() and not _mc.mesh_topology_file
          and topology_skeleton.skeleton_for_config(_mc) is not None)

# ── 15. Qt-free, in a subprocess ───────────────────────────────────────────
_probe = ("import sys; sys.path.insert(0, %r);"
          "import app.services.topology_cgrid, app.services.topology_cgrid_section;"
          "print('PyQt6' in sys.modules)" % _GUI)
_p2 = subprocess.run([sys.executable, "-c", _probe], capture_output=True, text=True,
                     cwd=_REPO)
check("15. importing the C-grid family and its section reader leaves PyQt6 "
      f"unimported (subprocess said {_p2.stdout.strip()!r}; in-process this check "
      "could only ever say 'loaded')", _p2.stdout.strip() == "False")

print()
if failures:
    print(f"FAILED {len(failures)} check(s)")
    sys.exit(1)
print("All checks passed.")
