"""Init-condition renderers (function initQ_at_p), IBM + non-IBM variants."""
from __future__ import annotations

from app.services.dll_templates_core import PROTO_INIT, _n


# --------------------------------------------------------------------------- #
# Init-condition renderers (function initQ_at_p)
# --------------------------------------------------------------------------- #
_INIT_HEAD = f"""//
//  unicones initial-condition DLL  (generated by HybMesh PreProcessor)
//
#include <cmath>
using namespace std;

{PROTO_INIT}

void
initQ_at_p(double x, double y, double z,
           double* Q, double* dQdt,
           double* dQdx, double* dQdy, double* dQdz) {{
  const int nvar = 5;
"""

_INIT_TAIL = """
  // Conservative vector Q = (rho, rho*u, rho*v, energy, phi)
  Q[0] = rho;
  Q[1] = rho * u;
  Q[2] = rho * v;
  Q[3] = p / (gamma - 1.0) + 0.5 * rho * (u * u + v * v + w * w);
  Q[4] = phi;

  for (int i = 0; i < nvar; ++i) { dQdt[i] = dQdx[i] = dQdy[i] = dQdz[i] = 0.0; }
}
"""


def _render_init_freestream(p: dict) -> str:
    return _INIT_HEAD + f"""  const double mach = {_n(p['mach'])};
  const double gamma = {_n(p['gamma'])};
  const double T = 1.0;

  double rho = {_n(p['rho'])};
  double u = {_n(p['u'])};
  double v = {_n(p['v'])};
  double w = {_n(p['w'])};
  double pres = rho * T / (gamma * mach * mach);
  double p = pres;          // pressure
  double phi = 0.0;         // no solid marking in this template
""" + _INIT_TAIL


def _render_init_rotating_disk(p: dict) -> str:
    return _INIT_HEAD + f"""  const double mach = {_n(p['mach'])};
  const double gamma = {_n(p['gamma'])};
  const double T = 1.0;
  const double x0 = {_n(p['cx'])};
  const double y0 = {_n(p['cy'])};
  const double radius = {_n(p['radius'])};
  const double ratio = {_n(p['ratio'])};   // edge velocity scale

  double rho = 1.0;
  double u = 1.0, v = 0.0, w = 0.0;
  double p = rho * T / (gamma * mach * mach);
  double phi = 0.0;

  double rx = x - x0, ry = y - y0;
  double rad = sqrt(rx * rx + ry * ry);
  if (rad * rad < radius * radius) {{        // inside the solid disk
    double ang = atan2(ry, rx);
    double Vel = rad / radius;
    phi = 1.0;
    u = -Vel * sin(ang) * ratio;
    v =  Vel * cos(ang) * ratio;
    w = 0.0;
  }}
""" + _INIT_TAIL


def _render_init_custom(p: dict) -> str:
    return _INIT_HEAD + """  const double mach = 0.2;
  const double gamma = 1.4;
  const double T = 1.0;

  double rho = 1.0;
  double u = 1.0, v = 0.0, w = 0.0;
  double p = rho * T / (gamma * mach * mach);
  double phi = 0.0;

  // TODO: set rho/u/v/w from (x, y, z); set phi = 1.0 inside the solid.
""" + _INIT_TAIL


def _render_init_solid_polygon(p: dict) -> str:
    """Freestream outside; a stationary solid polygon (phi = 1) inside, marked by
    a ray-crossing point-in-polygon test over the baked vertex list. ``verts`` is
    a list of (x, y) (open ring; a repeated closing vertex is dropped). Analytic —
    no phi.dat needed. Auto-generated from a CAD polygon/triangle/quad shape."""
    verts = [(float(x), float(y)) for x, y in (p.get("verts") or [])]
    if len(verts) >= 2 and verts[0] == verts[-1]:
        verts = verts[:-1]                      # ring wraps implicitly below
    nv = len(verts)
    vx = ", ".join(_n(x) for x, _ in verts) or "0.0"
    vy = ", ".join(_n(y) for _, y in verts) or "0.0"
    return _INIT_HEAD + f"""  const double mach = {_n(p.get('mach', 0.2))};
  const double gamma = {_n(p.get('gamma', 1.4))};
  const double T = 1.0;
  const int NV = {nv};
  const double VX[{max(nv, 1)}] = {{{vx}}};
  const double VY[{max(nv, 1)}] = {{{vy}}};

  double rho = 1.0;
  double u = 1.0, v = 0.0, w = 0.0;
  double p = rho * T / (gamma * mach * mach);
  double phi = 0.0;

  // Point-in-polygon (ray crossing): phi = 1 inside the solid, stationary (u=v=0).
  bool inside = false;
  for (int i = 0, j = NV - 1; i < NV; j = i++) {{
    if (((VY[i] > y) != (VY[j] > y)) &&
        (x < (VX[j] - VX[i]) * (y - VY[i]) / (VY[j] - VY[i]) + VX[i]))
      inside = !inside;
  }}
  if (inside) {{ phi = 1.0; u = 0.0; v = 0.0; w = 0.0; }}
""" + _INIT_TAIL


def render_analytic_phi_from_shape(shape_type: str, *, cx: float = 0.0,
                                   cy: float = 0.0, radius: float = 1.0,
                                   verts=None, mach: float = 0.2,
                                   gamma: float = 1.4, ratio: float = 0.0) -> str:
    """Render an init-condition DLL whose phi marks a solid derived analytically
    from a CAD shape — no STL3d phi.dat required. circle/arc -> solid disk
    (``ratio`` rotates it about its centre; 0 = stationary); polygon/triangle/
    quadrilateral -> point-in-polygon. Rides the normal init_cond_dll path."""
    st = (shape_type or "").lower()
    if st in ("circle", "arc"):
        return _render_init_rotating_disk(
            {"cx": cx, "cy": cy, "radius": radius, "ratio": ratio,
             "mach": mach, "gamma": gamma})
    return _render_init_solid_polygon(
        {"verts": verts or [], "mach": mach, "gamma": gamma})


# --- Non-IBM init-condition renderers (4-var Q, no solid phi) -------------- #
_INIT_HEAD_NOIBM = f"""//
//  unicones initial-condition DLL — pure fluid, NO immersed boundary
//  (generated by HybMesh PreProcessor)
//
#include <cmath>
using namespace std;

{PROTO_INIT}

void
initQ_at_p(double x, double y, double z,
           double* Q, double* dQdt,
           double* dQdx, double* dQdy, double* dQdz) {{
  const int nvar = 4;   // 2D fluid only — no solid-phase phi component
"""

_INIT_TAIL_NOIBM = """
  // Conservative vector Q = (rho, rho*u, rho*v, energy)   [no phi]
  Q[0] = rho;
  Q[1] = rho * u;
  Q[2] = rho * v;
  Q[3] = p / (gamma - 1.0) + 0.5 * rho * (u * u + v * v);

  for (int i = 0; i < nvar; ++i) { dQdt[i] = dQdx[i] = dQdy[i] = dQdz[i] = 0.0; }
}
"""


def _render_init_freestream_noibm(p: dict) -> str:
    return _INIT_HEAD_NOIBM + f"""  const double mach = {_n(p['mach'])};
  const double gamma = {_n(p['gamma'])};
  const double T = 1.0;

  double rho = {_n(p['rho'])};
  double u = {_n(p['u'])};
  double v = {_n(p['v'])};
  double p = rho * T / (gamma * mach * mach);
""" + _INIT_TAIL_NOIBM


def _render_init_shock_noibm(p: dict) -> str:
    return _INIT_HEAD_NOIBM + f"""  const double gamma = {_n(p['gamma'])};
  const double mach = {_n(p['mach'])};
  const double x0 = {_n(p['x0'])};        // shock at x = x0 (x < x0 = pre-shock)
  const double T2T1 = {_n(p['t2t1'])};    // post/pre temperature ratio
  const double r2r1 = {_n(p['r2r1'])};    // post/pre density ratio
  const double pre_p = 1.0 / (gamma * mach * mach);

  double rho, u, v, p;
  if (x < x0) {{                          // pre-shock (freestream)
    rho = 1.0; u = 1.0; v = 0.0;
    p = pre_p;
  }} else {{                              // post-shock
    rho = r2r1; u = 0.0; v = 0.0;
    p = rho * T2T1 / (gamma * mach * mach);
  }}
""" + _INIT_TAIL_NOIBM
