"""Authoritative C++ skeletons + parameter templates for unicones IBM DLLs.

The solver loads two kinds of user DLL via dlopen, each an ``extern "C"`` function
with a fixed signature (the implicit contract with the solver):

  * init-condition DLL  -> ``initQ_at_p(x,y,z, Q, dQdt, dQdx, dQdy, dQdz)``
        Q = (rho, rho*u, rho*v, energy, phi)   [2D, phi is the solid marker]
  * solid-motion DLL    -> ``get_6dof_vel(time, dt, p, center, force, torque,
                                          U, V, W, rho)``
        writes the solid velocity (U,V,W) and density at point p.

These signatures are kept here as the single source of truth so the GUI's
generated code always matches what the solver expects. If the solver changes a
prototype, update it here. Tier 1 = parameterised templates (no C++ needed);
Tier 2 = the user edits the generated source freely before compiling.

Pure Python, no Qt — importable by both the dialog and tests.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Callable

INIT_COND = "init_cond"
SOLID_MOTION = "motion"

# extern "C" prototypes echoed verbatim into every generated source.
PROTO_INIT = (
    'extern "C" void initQ_at_p(double x, double y, double z,\n'
    "                           double* Q, double* dQdt,\n"
    "                           double* dQdx, double* dQdy, double* dQdz);"
)
PROTO_MOTION = (
    'extern "C" void get_6dof_vel(double time, double dt, double* p,\n'
    "                             double* center, double* force, double* torque,\n"
    "                             double* U, double* V, double* W, double* rho);"
)


def _n(v) -> str:
    """Format a parameter as a C++ double literal."""
    return repr(float(v))


@dataclass
class ParamSpec:
    key: str
    label: str
    default: float
    decimals: int = 4
    tip: str = ""


@dataclass
class TemplateSpec:
    key: str
    label: str
    dll_type: str
    description: str
    render: Callable[[dict], str]
    params: list[ParamSpec] = field(default_factory=list)


# --------------------------------------------------------------------------- #
# Init-condition renderers (function initQ_at_p)
# --------------------------------------------------------------------------- #
_INIT_HEAD = f"""//
//  unicones initial-condition DLL  (generated by HybMesh PreProcessor)
//
#include <cmath>
using namespace std;

{PROTO_INIT}

void
initQ_at_p(double x, double y, double z,
           double* Q, double* dQdt,
           double* dQdx, double* dQdy, double* dQdz) {{
  const int nvar = 5;
"""

_INIT_TAIL = """
  // Conservative vector Q = (rho, rho*u, rho*v, energy, phi)
  Q[0] = rho;
  Q[1] = rho * u;
  Q[2] = rho * v;
  Q[3] = p / (gamma - 1.0) + 0.5 * rho * (u * u + v * v + w * w);
  Q[4] = phi;

  for (int i = 0; i < nvar; ++i) { dQdt[i] = dQdx[i] = dQdy[i] = dQdz[i] = 0.0; }
}
"""


def _render_init_freestream(p: dict) -> str:
    return _INIT_HEAD + f"""  const double mach = {_n(p['mach'])};
  const double gamma = {_n(p['gamma'])};
  const double T = 1.0;

  double rho = {_n(p['rho'])};
  double u = {_n(p['u'])};
  double v = {_n(p['v'])};
  double w = {_n(p['w'])};
  double pres = rho * T / (gamma * mach * mach);
  double p = pres;          // pressure
  double phi = 0.0;         // no solid marking in this template
""" + _INIT_TAIL


def _render_init_rotating_disk(p: dict) -> str:
    return _INIT_HEAD + f"""  const double mach = {_n(p['mach'])};
  const double gamma = {_n(p['gamma'])};
  const double T = 1.0;
  const double x0 = {_n(p['cx'])};
  const double y0 = {_n(p['cy'])};
  const double radius = {_n(p['radius'])};
  const double ratio = {_n(p['ratio'])};   // edge velocity scale

  double rho = 1.0;
  double u = 1.0, v = 0.0, w = 0.0;
  double p = rho * T / (gamma * mach * mach);
  double phi = 0.0;

  double rx = x - x0, ry = y - y0;
  double rad = sqrt(rx * rx + ry * ry);
  if (rad * rad < radius * radius) {{        // inside the solid disk
    double ang = atan2(ry, rx);
    double Vel = rad / radius;
    phi = 1.0;
    u = -Vel * sin(ang) * ratio;
    v =  Vel * cos(ang) * ratio;
    w = 0.0;
  }}
""" + _INIT_TAIL


def _render_init_custom(p: dict) -> str:
    return _INIT_HEAD + """  const double mach = 0.2;
  const double gamma = 1.4;
  const double T = 1.0;

  double rho = 1.0;
  double u = 1.0, v = 0.0, w = 0.0;
  double p = rho * T / (gamma * mach * mach);
  double phi = 0.0;

  // TODO: set rho/u/v/w from (x, y, z); set phi = 1.0 inside the solid.
""" + _INIT_TAIL


# --------------------------------------------------------------------------- #
# Solid-motion renderers (function get_6dof_vel)
# --------------------------------------------------------------------------- #
_MOTION_HEAD = f"""//
//  unicones solid-phase motion DLL  (generated by HybMesh PreProcessor)
//
#include <cmath>
using namespace std;

{PROTO_MOTION}

void
get_6dof_vel(double time, double dt, double* p,
             double* center, double* force, double* torque,
             double* U, double* V, double* W, double* rho) {{
"""
_MOTION_TAIL = "}\n"


def _render_motion_stationary(p: dict) -> str:
    return _MOTION_HEAD + """  U[0] = 0.0;
  V[0] = 0.0;
  W[0] = 0.0;
  *rho = 1.0;
""" + _MOTION_TAIL


def _render_motion_rotation(p: dict) -> str:
    return _MOTION_HEAD + f"""  const double x0 = {_n(p['cx'])};
  const double y0 = {_n(p['cy'])};
  const double radius = {_n(p['radius'])};   // velocity = 1 at this radius
  const double ratio = {_n(p['ratio'])};

  double rx = p[0] - x0, ry = p[1] - y0;
  double rad = sqrt(rx * rx + ry * ry);
  double ang = atan2(ry, rx);
  double Vel = rad / radius;
  U[0] = -Vel * sin(ang) * ratio;
  V[0] =  Vel * cos(ang) * ratio;
  W[0] = 0.0;                  // 2D rotation
  *rho = 1.0;
""" + _MOTION_TAIL


def _render_motion_translation(p: dict) -> str:
    return _MOTION_HEAD + f"""  U[0] = {_n(p['ux'])};
  V[0] = {_n(p['uy'])};
  W[0] = {_n(p['uz'])};
  *rho = 1.0;
""" + _MOTION_TAIL


def _render_motion_custom(p: dict) -> str:
    return _MOTION_HEAD + """  // p[0..2] = point coordinates; center[], force[], torque[] are inputs.
  // TODO: set the solid velocity at this point.
  U[0] = 0.0;
  V[0] = 0.0;
  W[0] = 0.0;
  *rho = 1.0;
""" + _MOTION_TAIL


# --------------------------------------------------------------------------- #
# Registry
# --------------------------------------------------------------------------- #
_MACH = ParamSpec("mach", "Mach", 0.2, 4, "Reference Mach number")
_GAMMA = ParamSpec("gamma", "gamma", 1.4, 4, "Ratio of specific heats")

TEMPLATES: dict[str, list[TemplateSpec]] = {
    INIT_COND: [
        TemplateSpec(
            "freestream", "Uniform freestream", INIT_COND,
            "Uniform flow everywhere; no solid marking (phi = 0).",
            _render_init_freestream,
            [_MACH, _GAMMA,
             ParamSpec("rho", "rho", 1.0), ParamSpec("u", "u", 1.0),
             ParamSpec("v", "v", 0.0), ParamSpec("w", "w", 0.0)]),
        TemplateSpec(
            "rotating_disk", "Rotating solid disk", INIT_COND,
            "Freestream outside; a rotating solid disk (phi = 1) inside the radius.",
            _render_init_rotating_disk,
            [ParamSpec("cx", "center x", 0.0), ParamSpec("cy", "center y", 0.0),
             ParamSpec("radius", "radius", 0.52), ParamSpec("ratio", "edge vel", 1.0),
             _MACH, _GAMMA]),
        TemplateSpec(
            "custom", "Custom (blank skeleton)", INIT_COND,
            "The correct prototype + a freestream default to edit freely.",
            _render_init_custom, []),
    ],
    SOLID_MOTION: [
        TemplateSpec(
            "stationary", "Stationary", SOLID_MOTION,
            "Solid does not move (U = V = W = 0).",
            _render_motion_stationary, []),
        TemplateSpec(
            "rotation", "Rigid rotation (2D)", SOLID_MOTION,
            "Rigid-body rotation about a center; velocity = 1 at the given radius.",
            _render_motion_rotation,
            [ParamSpec("cx", "center x", 0.0), ParamSpec("cy", "center y", 0.0),
             ParamSpec("radius", "radius", 0.52), ParamSpec("ratio", "edge vel", 1.0)]),
        TemplateSpec(
            "translation", "Translation", SOLID_MOTION,
            "Constant translational velocity.",
            _render_motion_translation,
            [ParamSpec("ux", "U", 1.0), ParamSpec("uy", "V", 0.0),
             ParamSpec("uz", "W", 0.0)]),
        TemplateSpec(
            "custom", "Custom (blank skeleton)", SOLID_MOTION,
            "The correct prototype + a zero-velocity default to edit freely.",
            _render_motion_custom, []),
    ],
}


def render_phi_field_init(*, xmin: float, ymin: float, zmin: float,
                          dx: float, dy: float, dz: float,
                          nx: int, ny: int, nz: int,
                          mach: float = 0.2, gamma: float = 1.4, u: float = 1.0,
                          us: float = 0.0, vs: float = 0.0, ws: float = 0.0,
                          phi_file: str = "phi.dat") -> str:
    """Generate an init-condition DLL that marks the solid from an STL3d phi field.

    The STL3d output is a structured Cartesian grid, so the grid spec is baked in
    and the lookup is an exact O(1) nearest-cell index into the flat phi array
    (file order i + Nx*(j + Ny*k)). Used by the STL3d -> Solver one-click hand-off;
    the phi data file is staged into the solver work dir as ``phi_file``.
    """
    return f"""//
//  unicones init-condition DLL — solid marked from an STL3d phi field
//  (generated by HybMesh PreProcessor; reads "{phi_file}" from the work dir)
//
#include <cmath>
#include <fstream>
#include <sstream>
#include <iostream>
#include <vector>
#include <string>
using namespace std;

{PROTO_INIT}

namespace {{
  // Cartesian grid spec baked in from STL3d (xg[i]=XMIN+i*DX, file order i,j,k).
  const double XMIN = {_n(xmin)}, YMIN = {_n(ymin)}, ZMIN = {_n(zmin)};
  const double DX = {_n(dx)}, DY = {_n(dy)}, DZ = {_n(dz)};
  const int NX = {int(nx)}, NY = {int(ny)}, NZ = {int(nz)};

  struct PhiField {{
    vector<double> phi;
    PhiField() {{
      ifstream in("{phi_file}");
      if (!in) {{ cerr << "[ibm] cannot open {phi_file}\\n"; return; }}
      phi.assign((size_t) NX * NY * NZ, 0.0);
      string line; double x, y, z, p; size_t n = 0;
      while (getline(in, line)) {{
        istringstream ss(line);
        if (ss >> x >> y >> z >> p) {{ if (n < phi.size()) phi[n] = p; ++n; }}
      }}
      cerr << "[ibm] loaded " << n << " phi points\\n";
    }}
    double at(double x, double y, double z) const {{
      if (phi.empty()) return 0.0;
      int i = DX > 0 ? (int) lround((x - XMIN) / DX) : 0;
      int j = DY > 0 ? (int) lround((y - YMIN) / DY) : 0;
      int k = DZ > 0 ? (int) lround((z - ZMIN) / DZ) : 0;
      if (i < 0) i = 0; if (i >= NX) i = NX - 1;
      if (j < 0) j = 0; if (j >= NY) j = NY - 1;
      if (k < 0) k = 0; if (k >= NZ) k = NZ - 1;
      size_t idx = (size_t) i + (size_t) NX * ((size_t) j + (size_t) NY * k);
      return idx < phi.size() ? phi[idx] : 0.0;
    }}
  }};
  static PhiField g_phi;   // loaded once at dlopen
}}

void
initQ_at_p(double x, double y, double z,
           double* Q, double* dQdt,
           double* dQdx, double* dQdy, double* dQdz) {{
  const int nvar = 5;
  const double mach = {_n(mach)};
  const double gamma = {_n(gamma)};
  const double T = 1.0;

  double rho = 1.0;
  double u = {_n(u)}, v = 0.0, w = 0.0;
  double p = rho * T / (gamma * mach * mach);

  double phi = g_phi.at(x, y, z);
  if (phi > 0.5) {{                 // inside the solid
    u = {_n(us)}; v = {_n(vs)}; w = {_n(ws)};
  }}

  Q[0] = rho;
  Q[1] = rho * u;
  Q[2] = rho * v;
  Q[3] = p / (gamma - 1.0) + 0.5 * rho * (u * u + v * v + w * w);
  Q[4] = phi;

  for (int i = 0; i < nvar; ++i) {{ dQdt[i] = dQdx[i] = dQdy[i] = dQdz[i] = 0.0; }}
}}
"""


def templates_for(dll_type: str) -> list[TemplateSpec]:
    return TEMPLATES.get(dll_type, [])


def default_basename(dll_type: str, template_key: str) -> str:
    prefix = "init_cond" if dll_type == INIT_COND else "motion"
    return f"{prefix}_{template_key}"
