"""Solid-motion renderers (function get_6dof_vel)."""
from __future__ import annotations

from app.services.dll_templates_core import PROTO_MOTION, _n


# --------------------------------------------------------------------------- #
# Solid-motion renderers (function get_6dof_vel)
# --------------------------------------------------------------------------- #
_MOTION_HEAD = f"""//
//  unicones solid-phase motion DLL  (generated by HybMesh PreProcessor)
//
#include <cmath>
using namespace std;

{PROTO_MOTION}

void
get_6dof_vel(double time, double dt, double* p,
             double* center, double* force, double* torque,
             double* U, double* V, double* W, double* rho) {{
"""
_MOTION_TAIL = "}\n"


def _render_motion_stationary(p: dict) -> str:
    return _MOTION_HEAD + """  U[0] = 0.0;
  V[0] = 0.0;
  W[0] = 0.0;
  *rho = 1.0;
""" + _MOTION_TAIL


def _render_motion_rotation(p: dict) -> str:
    return _MOTION_HEAD + f"""  const double x0 = {_n(p['cx'])};
  const double y0 = {_n(p['cy'])};
  const double radius = {_n(p['radius'])};   // velocity = 1 at this radius
  const double ratio = {_n(p['ratio'])};

  double rx = p[0] - x0, ry = p[1] - y0;
  double rad = sqrt(rx * rx + ry * ry);
  double ang = atan2(ry, rx);
  double Vel = rad / radius;
  U[0] = -Vel * sin(ang) * ratio;
  V[0] =  Vel * cos(ang) * ratio;
  W[0] = 0.0;                  // 2D rotation
  *rho = 1.0;
""" + _MOTION_TAIL


def _render_motion_translation(p: dict) -> str:
    return _MOTION_HEAD + f"""  U[0] = {_n(p['ux'])};
  V[0] = {_n(p['uy'])};
  W[0] = {_n(p['uz'])};
  *rho = 1.0;
""" + _MOTION_TAIL


def _render_motion_custom(p: dict) -> str:
    return _MOTION_HEAD + """  // p[0..2] = point coordinates; center[], force[], torque[] are inputs.
  // TODO: set the solid velocity at this point.
  U[0] = 0.0;
  V[0] = 0.0;
  W[0] = 0.0;
  *rho = 1.0;
""" + _MOTION_TAIL
