"""STL3d phi-field init-condition renderer (function initQ_at_p)."""
from __future__ import annotations

from app.services.dll_templates_core import PROTO_INIT, _n


def render_phi_field_init(*, xmin: float, ymin: float, zmin: float,
                          dx: float, dy: float, dz: float,
                          nx: int, ny: int, nz: int,
                          mach: float = 0.2, gamma: float = 1.4, u: float = 1.0,
                          us: float = 0.0, vs: float = 0.0, ws: float = 0.0,
                          phi_file: str = "phi.dat") -> str:
    """Generate an init-condition DLL that marks the solid from an STL3d phi field.

    The STL3d output is a structured Cartesian grid, so the grid spec is baked in
    and the lookup is an exact O(1) nearest-cell index into the flat phi array
    (file order i + Nx*(j + Ny*k)). Used by the STL3d -> Solver one-click hand-off;
    the phi data file is staged into the solver work dir as ``phi_file``.
    """
    return f"""//
//  unicones init-condition DLL — solid marked from an STL3d phi field
//  (generated by HybMesh PreProcessor; reads "{phi_file}" from the work dir)
//
#include <cmath>
#include <fstream>
#include <sstream>
#include <iostream>
#include <vector>
#include <string>
using namespace std;

{PROTO_INIT}

namespace {{
  // Cartesian grid spec baked in from STL3d (xg[i]=XMIN+i*DX, file order i,j,k).
  const double XMIN = {_n(xmin)}, YMIN = {_n(ymin)}, ZMIN = {_n(zmin)};
  const double DX = {_n(dx)}, DY = {_n(dy)}, DZ = {_n(dz)};
  const int NX = {int(nx)}, NY = {int(ny)}, NZ = {int(nz)};

  struct PhiField {{
    vector<double> phi;
    PhiField() {{
      ifstream in("{phi_file}");
      if (!in) {{ cerr << "[ibm] cannot open {phi_file}\\n"; return; }}
      phi.assign((size_t) NX * NY * NZ, 0.0);
      string line; double x, y, z, p; size_t n = 0;
      while (getline(in, line)) {{
        istringstream ss(line);
        if (ss >> x >> y >> z >> p) {{ if (n < phi.size()) phi[n] = p; ++n; }}
      }}
      cerr << "[ibm] loaded " << n << " phi points\\n";
    }}
    double at(double x, double y, double z) const {{
      if (phi.empty()) return 0.0;
      int i = DX > 0 ? (int) lround((x - XMIN) / DX) : 0;
      int j = DY > 0 ? (int) lround((y - YMIN) / DY) : 0;
      int k = DZ > 0 ? (int) lround((z - ZMIN) / DZ) : 0;
      if (i < 0) i = 0; if (i >= NX) i = NX - 1;
      if (j < 0) j = 0; if (j >= NY) j = NY - 1;
      if (k < 0) k = 0; if (k >= NZ) k = NZ - 1;
      size_t idx = (size_t) i + (size_t) NX * ((size_t) j + (size_t) NY * k);
      return idx < phi.size() ? phi[idx] : 0.0;
    }}
  }};
  static PhiField g_phi;   // loaded once at dlopen
}}

void
initQ_at_p(double x, double y, double z,
           double* Q, double* dQdt,
           double* dQdx, double* dQdy, double* dQdz) {{
  const int nvar = 5;
  const double mach = {_n(mach)};
  const double gamma = {_n(gamma)};
  const double T = 1.0;

  double rho = 1.0;
  double u = {_n(u)}, v = 0.0, w = 0.0;
  double p = rho * T / (gamma * mach * mach);

  double phi = g_phi.at(x, y, z);
  if (phi > 0.5) {{                 // inside the solid
    u = {_n(us)}; v = {_n(vs)}; w = {_n(ws)};
  }}

  Q[0] = rho;
  Q[1] = rho * u;
  Q[2] = rho * v;
  Q[3] = p / (gamma - 1.0) + 0.5 * rho * (u * u + v * v + w * w);
  Q[4] = phi;

  for (int i = 0; i < nvar; ++i) {{ dQdt[i] = dQdx[i] = dQdy[i] = dQdz[i] = 0.0; }}
}}
"""
