"""Boundary-condition renderers — BC type 11 (function getQ_inst_dll)."""
from __future__ import annotations

from app.services.dll_templates_core import PROTO_BC, _n


# --------------------------------------------------------------------------- #
# Boundary-condition renderers — BC type 11 (function getQ_inst_dll)
# Q = (rho, rho*u, rho*v, energy) [2D]; on entry Q holds the connecting cell's
# previous-step solution, overwrite it with the boundary state.
# --------------------------------------------------------------------------- #
_BC_HEAD = f"""//
//  unicones boundary-condition DLL — BC type 11 (user inflow/outflow)
//  (generated by HybMesh PreProcessor)   Q = (rho, rho*u, rho*v, energy) [2D]
//
#include <cmath>
using namespace std;

{PROTO_BC}

void
getQ_inst_dll(double t, double x, double y, double z,
              double* Q, double* dQdt,
              double* dQdx, double* dQdy, double* dQdz) {{
"""

_BC_TAIL = """
  Q[0] = rho;
  Q[1] = rho * u;
  Q[2] = rho * v;
  Q[3] = p / (gamma - 1.0) + 0.5 * rho * (u * u + v * v);

  for (int k = 0; k < 4; ++k) { dQdx[k] = dQdy[k] = dQdt[k] = 0.0; }
}
"""


def _render_bc_uniform(p: dict) -> str:
    return _BC_HEAD + f"""  // Fixed uniform inflow state.
  const double gamma = {_n(p['gamma'])};
  double rho = {_n(p['rho'])};
  double u = {_n(p['u'])};
  double v = {_n(p['v'])};
  double p = {_n(p['p'])};
""" + _BC_TAIL


def _render_bc_inflow_angle(p: dict) -> str:
    return _BC_HEAD + f"""  // Angled inflow holding stagnation conditions (cf. inflow_ang.cc).
  const double mach = {_n(p['mach'])};
  const double gamma = {_n(p['gamma'])};
  const double angle = {_n(p['angle_deg'])} / 180.0 * acos(-1.0);
  const double T0 = 1 + (gamma - 1) * 0.5 * mach * mach;
  const double p0 = pow(1 + (gamma-1)*0.5*mach*mach, gamma/(gamma-1)) / (gamma*mach*mach);
  const double U1 = cos(angle), V1 = sin(angle);
  double rho1 = fabs(Q[0]) < 1.e-12 ? 1 : Q[0];
  double u0 = fabs(Q[1]) < 1.e-12 ? U1 : Q[1] / rho1;
  double v0 = fabs(Q[2]) < 1.e-12 ? V1 : Q[2] / rho1;
  double e0 = fabs(Q[3]) < 1.e-13 ? 1./(gamma*mach*mach*(gamma-1)) + 0.5 : Q[3];
  double p_in = (gamma - 1) * (e0 - 0.5 * rho1 * (u0*u0 + v0*v0));
  double p_rat = p0 / p_in;
  double M2 = p_rat < 1 ? mach : sqrt(2/(gamma-1) * (pow(p_rat, (gamma-1)/gamma) - 1));
  double T2 = T0 / (1 + 0.5*(gamma-1)*M2*M2);
  double Vel = M2 * sqrt(T2) / mach;
  double u = Vel * cos(angle);
  double v = Vel * sin(angle);
  double p = p_in;
  double rho = gamma * mach * mach * p / T2;
""" + _BC_TAIL


def _render_bc_custom(p: dict) -> str:
    return _BC_HEAD + """  // On entry Q holds the connecting cell's previous-step solution; overwrite
  // it with the desired boundary state (rho, u, v, p), or blend with Q[..].
  const double gamma = 1.4;
  double rho = fabs(Q[0]) < 1.e-12 ? 1.0 : Q[0];
  double u = 1.0, v = 0.0, p = 1.0 / gamma;
  // TODO: set rho/u/v/p from (t, x, y, z).
""" + _BC_TAIL
