"""Fingerprint the input files a workspace depends on (Qt-free).

A workspace stores a session's *geometry points* alongside the path they were read
from. Nothing detected the two going out of step: if the ``.dat`` or ``.stl`` on
disk was re-exported from CAD, regenerated by a script, or edited by hand after the
workspace was saved, reopening it silently mixed a saved point array with a source
file that no longer matches — and the mesh stage, which re-reads from disk, would
then mesh geometry the user never saw on the canvas.

Storing a hash makes that detectable and reportable. It is deliberately only a
*report*: the file on disk may legitimately be the newer truth, so the user decides.

Cost note: hashing a 256 MB STL takes about a second, and autosave runs every 60 s.
:func:`fingerprint` therefore accepts a previous record and reuses its digest when
size and mtime are unchanged, so a repeated save is a stat() rather than a re-read.
"""
from __future__ import annotations

import hashlib
import os

# Read in chunks so a large STL never has to be held in memory at once.
_CHUNK = 1 << 20

#: Bumped if the record layout changes; readers tolerate an unknown/absent version
#: by treating the record as unverifiable rather than as a mismatch.
FINGERPRINT_VERSION = 1


def sha256_of(path: str) -> str:
    """Hex SHA-256 of a file's contents, or "" if it cannot be read."""
    try:
        h = hashlib.sha256()
        with open(path, "rb") as f:
            for block in iter(lambda: f.read(_CHUNK), b""):
                h.update(block)
        return h.hexdigest()
    except OSError:
        return ""


def fingerprint(path: str, previous: dict | None = None) -> dict:
    """Record identifying ``path``'s current contents.

    Returns ``{}`` for a missing/blank path — an in-memory (drawn) geometry has no
    source file, and that is not an error.

    ``previous`` is an earlier record for the same path: when its size and mtime
    still match, its digest is reused instead of re-hashing. mtime alone is not
    trusted as *proof* of sameness (it is cheap to preserve), which is why the
    digest is what gets compared on load — this is purely a cost optimisation for
    repeated autosaves.
    """
    if not path:
        return {}
    try:
        st = os.stat(path)
    except OSError:
        return {}

    size, mtime = st.st_size, int(st.st_mtime)
    if (previous and previous.get("sha256")
            and previous.get("size") == size and previous.get("mtime") == mtime):
        digest = previous["sha256"]
    else:
        digest = sha256_of(path)
        if not digest:
            return {}
    return {"version": FINGERPRINT_VERSION, "path": os.path.abspath(path),
            "size": size, "mtime": mtime, "sha256": digest}


def check(record: dict, path: str | None = None) -> tuple[str, str]:
    """Compare a stored record against the file now on disk.

    Returns ``(status, detail)`` where status is one of:

    * ``"ok"``          — contents identical to when the workspace was saved.
    * ``"unverified"``  — nothing to compare (no record, or an unknown version).
    * ``"missing"``     — the source file is gone.
    * ``"changed"``     — it exists but its contents differ.

    ``path`` overrides the recorded path, for a workspace opened after the project
    directory moved.
    """
    if not record or not isinstance(record, dict):
        return "unverified", ""
    if int(record.get("version", 0)) > FINGERPRINT_VERSION:
        # A newer writer may hash differently; a mismatch would be meaningless.
        return "unverified", (f"fingerprint version {record.get('version')} is newer "
                              f"than this build understands ({FINGERPRINT_VERSION})")
    target = path or record.get("path", "")
    if not target:
        return "unverified", ""
    if not os.path.exists(target):
        return "missing", target

    stored = record.get("sha256", "")
    if not stored:
        return "unverified", target
    # Fast path: identical size AND mtime means we can skip the read.
    try:
        st = os.stat(target)
        if st.st_size == record.get("size") and int(st.st_mtime) == record.get("mtime"):
            return "ok", target
    except OSError:
        return "missing", target

    if sha256_of(target) == stored:
        # Touched but not modified (a copy, a checkout, a re-save with no edit).
        return "ok", target
    return "changed", target


def describe(status: str, target: str, label: str = "") -> str:
    """A log line for a non-ok status, or "" when there is nothing to report."""
    who = label or os.path.basename(target) or target
    if status == "missing":
        return (f"[Integrity] [WARNING] '{who}' source file is missing "
                f"({target}). The saved geometry is still loaded, but re-running "
                "the CAD or mesh stage cannot read it.")
    if status == "changed":
        return (f"[Integrity] [WARNING] '{who}' has CHANGED on disk since this "
                f"workspace was saved ({target}). The canvas shows the saved "
                "points; the mesh stage would read the new file. Re-import to use "
                "the new version.")
    return ""
