from __future__ import annotations

# Text-file key -> (dataclass attribute, converter). Shared by MeshConfig
# (to_dict / load_from_dict) and the file I/O helpers in mesh_config_io.py.
# Kept in its own tiny module so mesh_config.py and mesh_config_io.py can both
# import it without a circular import.
_KEY_MAP = {
    "DOMAIN_X_MIN": ("domain_x_min", float),
    "DOMAIN_X_MAX": ("domain_x_max", float),
    "DOMAIN_Y_MIN": ("domain_y_min", float),
    "DOMAIN_Y_MAX": ("domain_y_max", float),
    "SURFACE_MESH_SIZE": ("surface_mesh_size", float),
    "AUTO_SURFACE_SIZE": ("auto_surface_size", lambda s: int(s) != 0),
    "FARFIELD_MESH_SIZE": ("farfield_mesh_size", float),
    "AUTO_FARFIELD_SIZE": ("auto_farfield_size", lambda s: int(s) != 0),
    "FARFIELD_GROWTH_RATE": ("farfield_growth_rate", float),
    "FARFIELD_BIDIRECTIONAL": ("farfield_bidirectional", lambda s: int(s) != 0),
    "FARFIELD_GROWTH_RATE_OUTER": ("farfield_growth_rate_outer", float),
    "BL_INITIAL_THICKNESS": ("bl_initial_thickness", float),
    "BL_GROWTH_RATE": ("bl_growth_rate", float),
    "BL_LAYERS": ("bl_layers", lambda s: int(float(s))),
    "BL_CONVEX_METHOD": ("bl_convex_method", lambda s: int(float(s))),
    "BL_FAN_NODES": ("bl_fan_nodes", lambda s: int(float(s))),
    "BL_AUTO_FAN_NODES": ("bl_auto_fan_nodes", lambda s: int(s) != 0),
    "BL_FAN_ANGLE_THRESHOLD": ("bl_fan_angle_threshold", float),
    "BL_CONVEX_ANGLE_THRESHOLD": ("bl_convex_angle_threshold", float),
    "BL_PARA_FALLBACK_ANGLE": ("bl_para_fallback_angle", float),
    "BL_CONCAVE_METHOD": ("bl_concave_method", lambda s: int(float(s))),
    "BL_CONCAVE_ANGLE_THRESHOLD": ("bl_concave_angle_threshold", float),
    "BL_CONCAVE_INFLUENCE_MULTIPLIER": ("bl_concave_influence_multiplier", float),
    "BL_JUNCTION_METHOD": ("bl_junction_method", lambda s: int(float(s))),
    "BL_JUNCTION_ANGLE_C1": ("bl_junction_angle_c1", float),
    "BL_JUNCTION_ANGLE_C2": ("bl_junction_angle_c2", float),
    "BL_JUNCTION_ANGLE_C3": ("bl_junction_angle_c3", float),
    "BL_MERGE_CONCAVE": ("bl_merge_concave", lambda s: int(s) != 0),
    "BL_SMOOTHING_ITERS": ("bl_smoothing_iters", lambda s: int(float(s))),
    "BL_TRANSITION_LAYERS": ("bl_transition_layers", lambda s: int(float(s))),
    "BL_AUTO_TRANSITION_LAYERS": ("bl_auto_transition_layers", lambda s: int(float(s))),
    "BL_TRANSITION_GROWTH_RATE": ("bl_transition_growth_rate", float),
    "BL_TRANSITION_BUFFER": ("bl_transition_buffer", float),
    "GMSH_ALGORITHM": ("gmsh_algorithm", lambda s: int(float(s))),
    "GMSH_OPTIMIZE": ("gmsh_optimize", lambda s: int(float(s))),
    "BL_USE_ANALYTIC_GEOM": ("bl_use_analytic_geom", lambda s: int(s) != 0),
    "BC_XMIN": ("bc_xmin", str),
    "BC_XMAX": ("bc_xmax", str),
    "BC_YMIN": ("bc_ymin", str),
    "BC_YMAX": ("bc_ymax", str),
    "BC_GEOM": ("bc_geom", str),
    "EXPORT_VTK": ("export_vtk", lambda s: int(s) != 0),
    "EXPORT_STARCD": ("export_starcd", lambda s: int(s) != 0),
    "EXPORT_CGNS": ("export_cgns", lambda s: int(s) != 0),
    "ENABLE_COLLISION_DETECTION": ("enable_collision_detection", lambda s: int(s) != 0),
    "OUTPUT_FILENAME": ("output_filename", str),
}
